(()=>{'use strict';
const K='designlineERP_v2',$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],N=x=>Number(x)||0,R=x=>'Rs '+N(x).toLocaleString('en-PK'),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=()=>{try{return JSON.parse(localStorage.getItem(K))||{}}catch{return{}}},write=db=>localStorage.setItem(K,JSON.stringify(db));
const C=(db,id)=>(db.customers||[]).find(x=>x.id===id)||{name:'Unknown',phone:'',area:''},V=(db,id)=>(db.vendors||[]).find(x=>x.id===id)||{name:'Unknown Vendor',phone:'',workType:''};
const flex=x=>['Flex Printing','Wallpaper + Fitting'].includes(x?.service),area=x=>N(x.widthFt)&&N(x.heightFt)?N(x.widthFt)*N(x.heightFt)*Math.max(1,N(x.panels)||1):N(x.qty);
function offsetCost(x){return N(x.printingCost)+N(x.plateQty)*N(x.plateRate)+N(x.dieCost)+N(x.laminationCost)+N(x.uvFoilCost)+N(x.cuttingCost)+N(x.bindingCost)+N(x.packingCost)+N(x.transportCost)+N(x.vendorCost)}
function lineTotal(x){if(flex(x))return area(x)*N(x.rate)+N(x.designCharges)+N(x.fittingCharges)+N(x.otherCharges);if(x.service==='Passport Photos')return N(x.qty)*N(x.rate)+N(x.retouchCharges)+N(x.otherCharges);if(x.service==='ID / Document Print')return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.laminationCharges)+N(x.otherCharges);return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.finishingCharges)+N(x.fittingCharges)+N(x.otherCharges)}
const lines=x=>(x.lineItems||[]).length?x.lineItems:[x],orderTotal=o=>lines(o).reduce((a,l)=>a+lineTotal(l),0),orderPaid=(db,o)=>N(o.advance)+(db.payments||[]).filter(p=>p.orderId===o.id).reduce((a,p)=>a+N(p.amount),0);
const pad=n=>String(N(n)).padStart(4,'0'),orderCode=o=>`ORD-${pad(o.orderNo)}`,quoteCode=q=>`QT-${pad(q.quoteNo)}`,invoiceCode=o=>`INV-${pad(o.invoiceNo)}`;
function ensureNumbers(){const db=read();db.meta=db.meta||{};let changed=false;const seed=(list,field,counter)=>{let max=Math.max(N(db.meta[counter]),...list.map(x=>N(x[field])),0);list.forEach(x=>{if(!N(x[field])){x[field]=++max;changed=true}});db.meta[counter]=max};seed(db.orders||[],'orderNo','orderSeq');seed(db.quotes||[],'quoteNo','quoteSeq');seed(db.orders||[],'invoiceNo','invoiceSeq');if(changed)write(db);return db}
function phonePK(p){return String(p||'').replace(/\D/g,'').replace(/^0/,'92')}
function toast(t){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1900)}
function injectStyle(){if($('#acct71style'))return;const s=document.createElement('style');s.id='acct71style';s.textContent=`#ordersView thead th:nth-child(7),#ordersView thead th:nth-child(8),#ordersBody td:nth-child(7),#ordersBody td:nth-child(8){display:none!important}.acct71-actions{display:flex;gap:7px;flex-wrap:wrap}.acct71-print{margin-left:4px}`;document.head.appendChild(s)}
function patchOrderTable(){const db=ensureNumbers(),head=$('#ordersView thead th:first-child');if(head&&head.textContent!=='Order No.')head.textContent='Order No.';$$('#ordersBody tr').forEach(tr=>{const b=tr.querySelector('[data-a="editOrder"]');if(!b)return;const o=(db.orders||[]).find(x=>x.id===b.dataset.id),td=tr.querySelector('td:first-child');if(!o||!td)return;const html=`<div class="row-main">${E(orderCode(o))}</div><div class="row-sub">${E(o.date||'')}</div>`;if(td.innerHTML!==html)td.innerHTML=html})}
function patchQuoteTable(){const db=ensureNumbers(),head=$('#quotationsView thead th:first-child');if(head&&head.textContent!=='Quotation No.')head.textContent='Quotation No.';$$('#quotesBody tr').forEach(tr=>{const b=tr.querySelector('[data-a="editQuote"]');if(!b)return;const q=(db.quotes||[]).find(x=>x.id===b.dataset.id),td=tr.querySelector('td:first-child');if(!q||!td)return;const html=`<div class="row-main">${E(quoteCode(q))}</div>`;if(td.innerHTML!==html)td.innerHTML=html})}
function patchDashboardNumbers(){const db=ensureNumbers();$$('#recentOrders .recent-item').forEach(el=>{const b=el.querySelector('[data-a="editOrder"]');if(!b)return;const o=(db.orders||[]).find(x=>x.id===b.dataset.id),t=el.querySelector('.item-title');if(o&&t){const v=`${orderCode(o)} — ${C(db,o.customerId).name}`;if(t.textContent!==v)t.textContent=v}});$$('#pendingBills .bill-item').forEach(el=>{const b=el.querySelector('[data-a="pay"]');if(!b)return;const o=(db.orders||[]).find(x=>x.id===b.dataset.id),sub=el.querySelector('.item-sub');if(o&&sub){const v=`${orderCode(o)} • Due ${o.due||'—'}`;if(sub.textContent!==v)sub.textContent=v}})}
function patchPaidBasisProfit(){const db=read(),cards=$$('#dashboardCards .stat-card');if(cards.length<4)return;const sales=(db.orders||[]).filter(o=>o.status!=='Cancelled').reduce((a,o)=>a+orderTotal(o),0),vp=(db.vendorPayments||[]).reduce((a,p)=>a+N(p.amount),0),exp=(db.expenses||[]).reduce((a,e)=>a+N(e.amount),0),net=sales-vp-exp;const c=cards[1],label=c.querySelector('.stat-label'),value=c.querySelector('.stat-value'),foot=c.querySelector('.stat-foot');if(label)label.textContent='Net Profit';if(value)value.textContent=R(net);if(foot)foot.textContent=`Sales − Vendor Paid ${R(vp)} − Expenses ${R(exp)}`;const efoot=cards[3]?.querySelector('.stat-foot');if(efoot)efoot.textContent=`Other expenses • Vendor paid ${R(vp)}`}
function vendorRows(db,id){const a=[];(db.orders||[]).forEach(o=>{lines(o).forEach(l=>{if(l.vendorId===id)a.push({date:o.date,order:o,customer:C(db,o.customerId).name,item:l.item||l.service,ref:l.vendorBillRef||'',cost:l.service==='Offset / Packaging'?offsetCost(l):N(l.vendorCost)})})});return a}
function vendorNumbers(db,id){const rows=vendorRows(db,id),cost=rows.reduce((a,x)=>a+N(x.cost),0),pays=(db.vendorPayments||[]).filter(p=>p.vendorId===id),paid=pays.reduce((a,p)=>a+N(p.amount),0);return{rows,pays,cost,paid,due:Math.max(0,cost-paid)}}
function vendorMessage(id){const db=ensureNumbers(),v=V(db,id),x=vendorNumbers(db,id);const jobs=x.rows.length?x.rows.map((r,i)=>`${i+1}. ${r.date||'—'} | ${orderCode(r.order)} | ${r.customer}\n   ${r.item}${r.ref?' | Ref: '+r.ref:''} | ${R(r.cost)}`).join('\n'):'No purchase/jobs recorded.';const pays=x.pays.length?x.pays.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))).map((p,i)=>`${i+1}. ${p.date||'—'} | ${R(p.amount)} | ${p.method||'Cash'}${p.reference?' | Ref: '+p.reference:''}`).join('\n'):'No payments recorded.';return `Assalam-o-Alaikum ${v.name},\n\nDesign Line Agency — Vendor Ledger Statement\n\nPURCHASE / JOBS\n${jobs}\n\nPAYMENT HISTORY\n${pays}\n\nTotal Purchase: ${R(x.cost)}\nTotal Paid: ${R(x.paid)}\nBalance Payable: ${R(x.due)}\n\nThank you.`}
function patchVendorLedger(){const title=$('#modalTitle');if(!title||!title.textContent.startsWith('Vendor Ledger'))return;const pay=$('#dynamicForm [data-v7="vendorPay"]');if(!pay)return;const id=pay.dataset.id,bar=pay.parentElement;if(!bar)return;bar.classList.add('acct71-actions');if(!bar.querySelector('[data-acct71="vendorWA"]')){const b=document.createElement('button');b.type='button';b.className='ghost';b.dataset.acct71='vendorWA';b.dataset.id=id;b.textContent='WhatsApp Statement';bar.insertBefore(b,pay)}if(!bar.querySelector('[data-acct71="vendorPrint"]')){const b=document.createElement('button');b.type='button';b.className='ghost acct71-print';b.dataset.acct71='vendorPrint';b.dataset.id=id;b.textContent='Print Statement';bar.insertBefore(b,pay)}}
function printVendor(id){const db=ensureNumbers(),v=V(db,id),x=vendorNumbers(db,id),s=db.settings||{},w=open('','_blank');if(!w)return;const jr=x.rows.map((r,i)=>`<tr><td>${i+1}</td><td>${E(r.date||'')}</td><td>${E(orderCode(r.order))}</td><td>${E(r.customer)}</td><td>${E(r.item)}</td><td>${E(r.ref||'—')}</td><td>${R(r.cost)}</td></tr>`).join('')||'<tr><td colspan="7">No purchases recorded.</td></tr>',pr=x.pays.slice().sort((a,b)=>String(a.date).localeCompare(String(b.date))).map((p,i)=>`<tr><td>${i+1}</td><td>${E(p.date||'')}</td><td>${R(p.amount)}</td><td>${E(p.method||'')}</td><td>${E(p.reference||'—')}</td><td>${E(p.note||'—')}</td></tr>`).join('')||'<tr><td colspan="6">No payments recorded.</td></tr>';w.document.write(`<!doctype html><html><head><title>Vendor Ledger ${E(v.name)}</title><style>@page{size:A4;margin:12mm}body{font-family:Arial;color:#161616}.head{border-bottom:3px solid #d71920;padding-bottom:12px}.head h1{color:#d71920;margin:0}.muted{font-size:11px;color:#666}.sum{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0}.sum div{border:1px solid #ddd;border-radius:8px;padding:10px}.sum b{display:block;font-size:18px;margin-top:4px}table{width:100%;border-collapse:collapse;margin:10px 0 20px}th,td{border:1px solid #ddd;padding:7px;font-size:10px;text-align:left}th{background:#17191d;color:#fff}h3{margin-top:20px}</style></head><body><div class="head"><h1>${E(s.invoiceBusinessName||s.agencyName||'Design Line Agency')}</h1><div class="muted">Vendor Ledger Statement • ${new Date().toLocaleDateString('en-PK')}</div></div><h2>${E(v.name)}</h2><div class="muted">${E(v.phone||'')} ${v.workType?' • '+E(v.workType):''}</div><div class="sum"><div>Total Purchase<b>${R(x.cost)}</b></div><div>Total Paid<b>${R(x.paid)}</b></div><div>Balance Payable<b>${R(x.due)}</b></div></div><h3>Purchase / Jobs</h3><table><thead><tr><th>#</th><th>Date</th><th>Order No.</th><th>Customer</th><th>Item</th><th>Ref</th><th>Cost</th></tr></thead><tbody>${jr}</tbody></table><h3>Payment History</h3><table><thead><tr><th>#</th><th>Date</th><th>Amount</th><th>Method</th><th>Reference</th><th>Note</th></tr></thead><tbody>${pr}</tbody></table><script>window.onload=()=>print()<\/script></body></html>`);w.document.close()}
function customerMessage(id){const db=ensureNumbers(),c=C(db,id),os=(db.orders||[]).filter(o=>o.customerId===id&&o.status!=='Cancelled');let gt=0,gp=0;const body=os.map((o,i)=>{const t=orderTotal(o),p=orderPaid(db,o);gt+=t;gp+=p;return `${i+1}. ${orderCode(o)} | ${R(t)} | Paid ${R(p)} | Balance ${R(Math.max(0,t-p))}`}).join('\n');return `Assalam-o-Alaikum ${c.name},\n\nDesign Line Agency — Order Statement\n${body||'No active orders.'}\n\nGrand Total: ${R(gt)}\nReceived: ${R(gp)}\nPending: ${R(Math.max(0,gt-gp))}`}
function quoteMessage(id){const db=ensureNumbers(),q=(db.quotes||[]).find(x=>x.id===id);if(!q)return'';const c=C(db,q.customerId),total=lines(q).reduce((a,l)=>a+lineTotal(l),0);return `Assalam-o-Alaikum ${c.name},\n\nDesign Line Agency — Quotation ${quoteCode(q)}\n${lines(q).map((l,i)=>`${i+1}. ${l.item||l.service} — ${R(lineTotal(l))}`).join('\n')}\n\nQuotation Total: ${R(total)}\nStatus: ${q.status||'Draft'}`}
function orderWAMessage(id){const db=ensureNumbers(),o=(db.orders||[]).find(x=>x.id===id);if(!o)return'';const c=C(db,o.customerId),t=orderTotal(o),p=orderPaid(db,o);return `Assalam-o-Alaikum ${c.name},\n\nDesign Line Agency — ${orderCode(o)}\n${lines(o).map((l,i)=>`${i+1}. ${l.item||l.service} — ${R(lineTotal(l))}`).join('\n')}\n\nTotal: ${R(t)}\nPaid: ${R(p)}\nBalance: ${R(Math.max(0,t-p))}\nDelivery: ${o.due||'—'}`}
function intercept(e){const v=e.target.closest?.('[data-acct71]');if(v){e.preventDefault();e.stopImmediatePropagation();const id=v.dataset.id;if(v.dataset.acct71==='vendorWA'){const db=read(),ven=V(db,id);if(!ven.phone)return toast('Vendor phone number missing');return window.open(`https://wa.me/${phonePK(ven.phone)}?text=${encodeURIComponent(vendorMessage(id))}`,'_blank')}if(v.dataset.acct71==='vendorPrint')return printVendor(id)}const c=e.target.closest?.('[data-v7="customerWA"]');if(c){e.preventDefault();e.stopImmediatePropagation();const db=read(),cu=C(db,c.dataset.id);if(!cu.phone)return toast('Customer phone missing');return window.open(`https://wa.me/${phonePK(cu.phone)}?text=${encodeURIComponent(customerMessage(c.dataset.id))}`,'_blank')}const q=e.target.closest?.('[data-v7="quoteWA"]');if(q){e.preventDefault();e.stopImmediatePropagation();const db=read(),qt=(db.quotes||[]).find(x=>x.id===q.dataset.id),cu=C(db,qt?.customerId);if(!cu.phone)return toast('Customer phone missing');return window.open(`https://wa.me/${phonePK(cu.phone)}?text=${encodeURIComponent(quoteMessage(q.dataset.id))}`,'_blank')}const o=e.target.closest?.('[data-a="wa"]');if(o){e.preventDefault();e.stopImmediatePropagation();const db=read(),ord=(db.orders||[]).find(x=>x.id===o.dataset.id),cu=C(db,ord?.customerId);if(!cu.phone)return toast('Customer phone missing');return window.open(`https://wa.me/${phonePK(cu.phone)}?text=${encodeURIComponent(orderWAMessage(o.dataset.id))}`,'_blank')}}
let busy=false;function patch(){if(busy)return;busy=true;setTimeout(()=>{ensureNumbers();injectStyle();patchOrderTable();patchQuoteTable();patchDashboardNumbers();patchPaidBasisProfit();patchVendorLedger();busy=false},50)}
function init(){ensureNumbers();injectStyle();window.addEventListener('click',intercept,true);patch();new MutationObserver(patch).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();