(()=>{'use strict';
const K='designlineERP_v2',$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const N=x=>Number(x)||0,R=x=>'Rs '+N(x).toLocaleString('en-PK'),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const D=(d=new Date())=>{const p=x=>String(x).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const read=()=>{try{return JSON.parse(localStorage.getItem(K))||{}}catch(e){return{}}};
const write=db=>localStorage.setItem(K,JSON.stringify(db));
const lines=o=>(o?.lineItems||[]).length?o.lineItems:[o||{}];
const flex=x=>['Flex Printing','Wallpaper + Fitting'].includes(x?.service);
const area=x=>N(x.widthFt)&&N(x.heightFt)?N(x.widthFt)*N(x.heightFt)*Math.max(1,N(x.panels)||1):N(x.qty);
function lineTotal(x){const s=x?.service||'Other';if(flex(x))return area(x)*N(x.rate)+N(x.designCharges)+N(x.fittingCharges)+N(x.otherCharges);if(s==='Passport Photos')return N(x.qty)*N(x.rate)+N(x.retouchCharges)+N(x.otherCharges);if(s==='ID / Document Print')return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.laminationCharges)+N(x.otherCharges);return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.finishingCharges)+N(x.fittingCharges)+N(x.otherCharges)}
const orderTotal=o=>lines(o).reduce((a,l)=>a+lineTotal(l),0);
const orderPaid=(db,o)=>N(o.advance)+(db.payments||[]).filter(p=>p.orderId===o.id).reduce((a,p)=>a+N(p.amount),0);
const pad=n=>String(N(n)).padStart(4,'0'),orderCode=o=>`ORD-${pad(o.orderNo)}`,quoteCode=q=>`QT-${pad(q.quoteNo)}`,invoiceCode=o=>`INV-${pad(o.invoiceNo)}`;
function ensureNumbers(){const db=read();db.meta=db.meta||{};let changed=false;const seed=(list,field,counter)=>{let max=Math.max(N(db.meta[counter]),...list.map(x=>N(x[field])),0);for(const x of list){if(!N(x[field])){x[field]=++max;changed=true}}db.meta[counter]=max};seed(db.orders||[],'orderNo','orderSeq');seed(db.quotes||[],'quoteNo','quoteSeq');seed(db.orders||[],'invoiceNo','invoiceSeq');if(changed)write(db);return db}
function setText(el,text){if(el&&el.textContent!==String(text))el.textContent=String(text)}
function setCard(card,label,value,foot){if(!card)return;setText(card.querySelector('.stat-label'),label);setText(card.querySelector('.stat-value'),R(value));if(foot!==undefined)setText(card.querySelector('.stat-foot'),foot)}
function injectStyle(){if($('#acctV12Style'))return;const s=document.createElement('style');s.id='acctV12Style';s.textContent='#ordersView thead th:nth-child(7),#ordersView thead th:nth-child(8),#ordersBody td:nth-child(7),#ordersBody td:nth-child(8){display:none!important}.acct-v12-actions{display:flex;gap:7px;flex-wrap:wrap}';document.head.appendChild(s)}
function patchNumbers(){const db=ensureNumbers();$$('#ordersBody tr').forEach(tr=>{const b=tr.querySelector('[data-a="editOrder"]');if(!b)return;const o=(db.orders||[]).find(x=>x.id===b.dataset.id),td=tr.querySelector('td:first-child');if(!o||!td)return;const main=td.querySelector('.row-main');if(main)setText(main,orderCode(o))});$$('#quotesBody tr').forEach(tr=>{const b=tr.querySelector('[data-a="editQuote"]');if(!b)return;const q=(db.quotes||[]).find(x=>x.id===b.dataset.id),td=tr.querySelector('td:first-child');if(!q||!td)return;const main=td.querySelector('.row-main')||td;if(main)setText(main,quoteCode(q))})}
function patchDashboard(){const db=read(),cards=$$('#dashboardCards .stat-card');if(cards.length<4)return;const orders=(db.orders||[]).filter(o=>o.status!=='Cancelled'),sales=orders.reduce((a,o)=>a+orderTotal(o),0),received=orders.reduce((a,o)=>a+orderPaid(db,o),0),pending=orders.reduce((a,o)=>a+Math.max(0,orderTotal(o)-orderPaid(db,o)),0),vp=(db.vendorPayments||[]).reduce((a,p)=>a+N(p.amount),0),exp=(db.expenses||[]).reduce((a,e)=>a+N(e.amount),0),net=sales-vp-exp;setCard(cards[0],'Total Sales',sales,`${orders.length} orders`);setCard(cards[1],'Received',received,'Customer collections');setCard(cards[2],'Pending Bills',pending,`${orders.filter(o=>Math.max(0,orderTotal(o)-orderPaid(db,o))>0).length} orders`);setCard(cards[3],'Net Profit',net,`Sales − Vendor Paid ${R(vp)} − Expenses ${R(exp)}`)}
function bounds(){const t=$('#reportRange')?.value||'month',n=new Date(),today=D();if(t==='all')return['0000-01-01','9999-12-31'];if(t==='today')return[today,today];if(t==='week'){const s=new Date(n);s.setDate(n.getDate()-((n.getDay()+6)%7));return[D(s),today]}if(t==='month')return[`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-01`,today];if(t==='year')return[`${n.getFullYear()}-01-01`,`${n.getFullYear()}-12-31`];return[$('#v7From')?.value||today,$('#v7To')?.value||today]}
const within=(d,a,b)=>d&&d>=a&&d<=b;
function patchReports(){if(!$('#reportsView')?.classList.contains('active'))return;const db=read(),[a,b]=bounds(),orders=(db.orders||[]).filter(o=>o.status!=='Cancelled'&&within(o.date,a,b)),vps=(db.vendorPayments||[]).filter(p=>within(p.date,a,b)),exps=(db.expenses||[]).filter(e=>within(e.date,a,b)),sales=orders.reduce((s,o)=>s+orderTotal(o),0),received=orders.reduce((s,o)=>s+orderPaid(db,o),0),pending=orders.reduce((s,o)=>s+Math.max(0,orderTotal(o)-orderPaid(db,o)),0),vp=vps.reduce((s,p)=>s+N(p.amount),0),exp=exps.reduce((s,e)=>s+N(e.amount),0),net=sales-vp-exp;for(const c of $$('#reportCards .stat-card')){const label=(c.querySelector('.stat-label')?.textContent||'').trim().toLowerCase();if(label==='sales')setCard(c,'Sales',sales,`${a} to ${b}`);else if(label==='received')setCard(c,'Received',received,`${a} to ${b}`);else if(label==='customer pending')setCard(c,'Customer Pending',pending,`${a} to ${b}`);else if(label==='vendor payments')setCard(c,'Vendor Payments',vp,`${a} to ${b}`);else if(label==='expenses')setCard(c,'Expenses',exp,`${a} to ${b}`);else if(label==='net profit')setCard(c,'Net Profit',net,`Sales − Vendor Payments − Expenses • ${a} to ${b}`)}for(const tr of $$('#v7Breakdown tr')){const td=tr.querySelectorAll('td');if(td.length<8)continue;const money=i=>N((td[i].textContent||'').replace(/[^0-9.-]/g,''));setText(td[7],R(money(1)-money(5)-money(6)))}}
function phonePK(p){return String(p||'').replace(/\D/g,'').replace(/^0/,'92')}
function vendorRows(db,id){const out=[];(db.orders||[]).forEach(o=>lines(o).forEach(l=>{if(l.vendorId===id)out.push({date:o.date,order:o,item:l.item||l.service,customer:(db.customers||[]).find(c=>c.id===o.customerId)?.name||'Unknown',ref:l.vendorBillRef||l.purchaseBillRef||'',cost:N(l.vendorCost)})}));return out}
function vendorNumbers(db,id){const rows=vendorRows(db,id),pays=(db.vendorPayments||[]).filter(p=>p.vendorId===id),cost=rows.reduce((a,x)=>a+N(x.cost),0),paid=pays.reduce((a,x)=>a+N(x.amount),0);return{rows,pays,cost,paid,due:Math.max(0,cost-paid)}}
function vendorMessage(id){const db=ensureNumbers(),v=(db.vendors||[]).find(x=>x.id===id)||{},x=vendorNumbers(db,id),jobs=x.rows.length?x.rows.map((r,i)=>`${i+1}. ${r.date||'—'} | ${orderCode(r.order)} | ${r.customer}\n   ${r.item}${r.ref?' | Ref: '+r.ref:''} | ${R(r.cost)}`).join('\n'):'No purchase/jobs recorded.',pays=x.pays.length?x.pays.map((p,i)=>`${i+1}. ${p.date||'—'} | ${R(p.amount)} | ${p.method||'Cash'}${p.reference?' | Ref: '+p.reference:''}`).join('\n'):'No payments recorded.';return `Assalam-o-Alaikum ${v.name||''},\n\nDesign Line Agency — Vendor Ledger Statement\n\nPURCHASE / JOBS\n${jobs}\n\nPAYMENT HISTORY\n${pays}\n\nTotal Purchase: ${R(x.cost)}\nTotal Paid: ${R(x.paid)}\nBalance Payable: ${R(x.due)}\n\nThank you.`}
function printVendor(id){const db=ensureNumbers(),v=(db.vendors||[]).find(x=>x.id===id)||{},x=vendorNumbers(db,id),s=db.settings||{},w=open('','_blank');if(!w)return;const jr=x.rows.map((r,i)=>`<tr><td>${i+1}</td><td>${E(r.date||'')}</td><td>${E(orderCode(r.order))}</td><td>${E(r.customer)}</td><td>${E(r.item)}</td><td>${E(r.ref||'—')}</td><td>${R(r.cost)}</td></tr>`).join('')||'<tr><td colspan="7">No purchases recorded.</td></tr>',pr=x.pays.map((p,i)=>`<tr><td>${i+1}</td><td>${E(p.date||'')}</td><td>${R(p.amount)}</td><td>${E(p.method||'')}</td><td>${E(p.reference||'—')}</td></tr>`).join('')||'<tr><td colspan="5">No payments recorded.</td></tr>';w.document.write(`<!doctype html><html><head><title>Vendor Ledger</title><style>@page{size:A4;margin:12mm}body{font-family:Arial;color:#161616}h1{color:#d71920}table{width:100%;border-collapse:collapse;margin:12px 0 20px}th,td{border:1px solid #ddd;padding:7px;font-size:10px;text-align:left}th{background:#17191d;color:#fff}.sum{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.sum div{border:1px solid #ddd;padding:10px;border-radius:8px}</style></head><body><h1>${E(s.invoiceBusinessName||s.agencyName||'Design Line Agency')}</h1><h2>${E(v.name||'Vendor')}</h2><div>${E(v.phone||'')}</div><div class="sum"><div>Total Purchase<br><b>${R(x.cost)}</b></div><div>Total Paid<br><b>${R(x.paid)}</b></div><div>Payable<br><b>${R(x.due)}</b></div></div><h3>Jobs / Purchases</h3><table><thead><tr><th>#</th><th>Date</th><th>Order</th><th>Customer</th><th>Item</th><th>Ref</th><th>Cost</th></tr></thead><tbody>${jr}</tbody></table><h3>Payments</h3><table><thead><tr><th>#</th><th>Date</th><th>Amount</th><th>Method</th><th>Reference</th></tr></thead><tbody>${pr}</tbody></table><script>window.onload=()=>print()<\/script></body></html>`);w.document.close()}
function patchVendorLedger(){const title=$('#modalTitle');if(!title||!title.textContent.startsWith('Vendor Ledger'))return;const pay=$('#dynamicForm [data-v7="vendorPay"]');if(!pay)return;const id=pay.dataset.id,bar=pay.parentElement;if(!bar)return;bar.classList.add('acct-v12-actions');if(!bar.querySelector('[data-v12="vendorWA"]')){const b=document.createElement('button');b.type='button';b.className='ghost';b.dataset.v12='vendorWA';b.dataset.id=id;b.textContent='WhatsApp Statement';bar.insertBefore(b,pay)}if(!bar.querySelector('[data-v12="vendorPrint"]')){const b=document.createElement('button');b.type='button';b.className='ghost';b.dataset.v12='vendorPrint';b.dataset.id=id;b.textContent='Print Statement';bar.insertBefore(b,pay)}}
function click(e){const b=e.target.closest?.('[data-v12]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const id=b.dataset.id;if(b.dataset.v12==='vendorPrint')return printVendor(id);if(b.dataset.v12==='vendorWA'){const db=read(),v=(db.vendors||[]).find(x=>x.id===id)||{};if(!v.phone)return;window.open(`https://wa.me/${phonePK(v.phone)}?text=${encodeURIComponent(vendorMessage(id))}`,'_blank')}}
let timer=null,busy=false;function patch(){clearTimeout(timer);timer=setTimeout(()=>{if(busy)return;busy=true;try{injectStyle();patchNumbers();patchDashboard();patchReports();patchVendorLedger()}finally{busy=false}},40)}
function init(){injectStyle();ensureNumbers();document.addEventListener('click',click,true);document.addEventListener('change',e=>{if(['reportRange','v7From','v7To'].includes(e.target?.id))patch()},true);patch();new MutationObserver(patch).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();