(()=>{'use strict';
const K='designlineERP_v2',$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const N=x=>Number(x)||0,R=x=>'Rs '+N(x).toLocaleString('en-PK'),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const D=(d=new Date())=>{const p=x=>String(x).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const read=()=>{try{return JSON.parse(localStorage.getItem(K))||{}}catch(e){return{}}};
const lines=o=>(o?.lineItems||[]).length?o.lineItems:[o||{}];
const flex=x=>['Flex Printing','Wallpaper + Fitting'].includes(x?.service);
const area=x=>N(x.widthFt)&&N(x.heightFt)?N(x.widthFt)*N(x.heightFt)*Math.max(1,N(x.panels)||1):N(x.qty);
function lineSale(x){const s=x?.service||'Other';if(flex(x))return area(x)*N(x.rate)+N(x.designCharges)+N(x.fittingCharges)+N(x.otherCharges);if(s==='Passport Photos')return N(x.qty)*N(x.rate)+N(x.retouchCharges)+N(x.otherCharges);if(s==='ID / Document Print')return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.laminationCharges)+N(x.otherCharges);return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.finishingCharges)+N(x.fittingCharges)+N(x.otherCharges)}
function offsetDirect(x){return N(x.printingCost)+N(x.plateQty)*N(x.plateRate)+N(x.dieCost)+N(x.laminationCost)+N(x.uvFoilCost)+N(x.cuttingCost)+N(x.bindingCost)+N(x.packingCost)+N(x.transportCost)+N(x.vendorCost)}
function lineDirect(x){return x?.service==='Offset / Packaging'?offsetDirect(x):N(x?.vendorCost)}
const orderSale=o=>lines(o).reduce((a,l)=>a+lineSale(l),0);
const orderDirect=o=>lines(o).reduce((a,l)=>a+lineDirect(l),0);
const orderPaid=(db,o)=>N(o.advance)+(db.payments||[]).filter(p=>p.orderId===o.id).reduce((a,p)=>a+N(p.amount),0);
const within=(d,a,b)=>d&&d>=a&&d<=b;
function linkedVendorCost(db){let t=0;(db.orders||[]).forEach(o=>lines(o).forEach(l=>{if(l.vendorId)t+=N(l.vendorCost)}));return t}
function metrics(db,from='0000-01-01',to='9999-12-31'){
 const os=(db.orders||[]).filter(o=>o.status!=='Cancelled'&&within(o.date,from,to));
 const es=(db.expenses||[]).filter(e=>within(e.date,from,to));
 const vps=(db.vendorPayments||[]).filter(p=>within(p.date,from,to));
 const sales=os.reduce((a,o)=>a+orderSale(o),0),received=os.reduce((a,o)=>a+orderPaid(db,o),0),receivable=os.reduce((a,o)=>a+Math.max(0,orderSale(o)-orderPaid(db,o)),0),direct=os.reduce((a,o)=>a+orderDirect(o),0),expenses=es.reduce((a,e)=>a+N(e.amount),0),vendorPaid=vps.reduce((a,p)=>a+N(p.amount),0),gross=sales-direct,net=gross-expenses;
 let vendorCost=0;os.forEach(o=>lines(o).forEach(l=>{if(l.vendorId)vendorCost+=N(l.vendorCost)}));
 return{orders:os,expensesRows:es,vendorPayments:vps,sales,received,receivable,direct,gross,expenses,net,vendorPaid,vendorCost,vendorPayable:Math.max(0,vendorCost-vendorPaid)};
}
function allMetrics(db){const m=metrics(db);const allVendorCost=linkedVendorCost(db),allVendorPaid=(db.vendorPayments||[]).reduce((a,p)=>a+N(p.amount),0);m.vendorCost=allVendorCost;m.vendorPaid=allVendorPaid;m.vendorPayable=Math.max(0,allVendorCost-allVendorPaid);return m}
function card(label,value,foot,accent=''){return `<div class="stat-card v14-card"${accent?` style="--accent:${accent}"`:''}><div class="stat-top"><span class="stat-label">${E(label)}</span></div><strong class="stat-value">${R(value)}</strong><div class="stat-foot">${E(foot||'')}</div></div>`}
function injectStyle(){if($('#acctV14Style'))return;const s=document.createElement('style');s.id='acctV14Style';s.textContent=`
#dashboardCards.v14-dashboard{grid-template-columns:repeat(4,minmax(0,1fr))}.v14-card .stat-value{font-size:23px}.v14-finance{margin:14px 0}.v14-equation{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;align-items:stretch}.v14-equation>div{padding:12px;border:1px solid var(--line);border-radius:12px;background:var(--surface-2)}.v14-equation span{display:block;color:var(--muted);font-size:10px;font-weight:800;text-transform:uppercase}.v14-equation b{display:block;font-size:16px;margin-top:6px}.v14-note{margin-top:10px;font-size:11px;color:var(--muted);line-height:1.5}.v14-tax-toolbar{display:flex;gap:9px;align-items:end;flex-wrap:wrap;margin:12px 0}.v14-tax-toolbar label{min-width:190px}.v14-tax-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:12px 0}.v14-tax-box{padding:12px;border:1px solid var(--line);border-radius:12px;background:var(--surface-2)}.v14-tax-box span{display:block;font-size:10px;color:var(--muted);font-weight:800}.v14-tax-box b{display:block;font-size:19px;margin-top:5px}.v14-table{overflow:auto;border:1px solid var(--line);border-radius:12px;margin-top:12px}.v14-table table{min-width:760px}.v14-table th,.v14-table td{white-space:nowrap}.v14-expenses{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px 14px;margin-top:10px}.v14-exp-row{display:flex;justify-content:space-between;gap:12px;border-bottom:1px dashed var(--line);padding:6px 0;font-size:11px}@media(max-width:1000px){#dashboardCards.v14-dashboard,.v14-tax-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.v14-equation{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){#dashboardCards.v14-dashboard,.v14-tax-grid,.v14-equation,.v14-expenses{grid-template-columns:1fr}.v14-card .stat-value{font-size:20px}}
`;document.head.appendChild(s)}
let dashSig='';
function renderDashboard(force=false){const box=$('#dashboardCards');if(!box)return;const db=read(),m=allMetrics(db),sig=JSON.stringify([m.sales,m.received,m.receivable,m.direct,m.gross,m.expenses,m.net,m.vendorPayable,m.vendorPaid,(db.orders||[]).length,(db.expenses||[]).length,(db.vendorPayments||[]).length]);if(!force&&sig===dashSig&&box.dataset.v14==='1')return;dashSig=sig;box.dataset.v14='1';box.classList.add('v14-dashboard');box.innerHTML=card('Total Sales',m.sales,`${m.orders.length} active orders`,'#3077d5')+card('Received',m.received,'Customer collections received','#14945c')+card('Customer Receivable',m.receivable,'Still to collect from customers','#e31b23')+card('Direct / Production Cost',m.direct,'Vendor + job production cost','#d98324')+card('Gross Profit',m.gross,'Sales − direct production cost','#7457d9')+card('Office / Other Expenses',m.expenses,'Rent, salary, material, fuel, utilities etc.','#b95d2a')+card('Net Profit',m.net,'Gross profit − office/other expenses','#14945c')+card('Vendor Payable',m.vendorPayable,`Vendor paid ${R(m.vendorPaid)}`,'#e31b23');
 let p=$('#v14FinancePanel');if(!p){p=document.createElement('div');p.id='v14FinancePanel';p.className='panel v14-finance';box.insertAdjacentElement('afterend',p)}p.innerHTML=`<div class="panel-head"><div><span class="section-kicker">PROFIT STRUCTURE</span><h3>Business Profit Calculation</h3></div></div><div class="v14-equation"><div><span>Total Sales</span><b>${R(m.sales)}</b></div><div><span>Less: Direct Cost</span><b>${R(m.direct)}</b></div><div><span>Gross Profit</span><b>${R(m.gross)}</b></div><div><span>Less: Expenses</span><b>${R(m.expenses)}</b></div><div><span>Net Profit</span><b>${R(m.net)}</b></div></div><div class="v14-note"><b>Vendor payment note:</b> Vendor / purchase cost profit me Direct Cost ke andar minus hoti hai. Vendor ko payment karna us payable ko settle karta hai, is liye payment ko dobara Net Profit se minus nahi kiya jata. Office aur material expenses jo Expenses module me enter honge, woh Net Profit se minus honge.</div>`;
}
function currentTaxYear(){const n=new Date();return n.getMonth()>=6?n.getFullYear()+1:n.getFullYear()}
function taxBounds(y){return[`${y-1}-07-01`,`${y}-06-30`]}
function monthKeys(y){const out=[];for(let m=7;m<=12;m++)out.push(`${y-1}-${String(m).padStart(2,'0')}`);for(let m=1;m<=6;m++)out.push(`${y}-${String(m).padStart(2,'0')}`);return out}
function monthLabel(k){const [y,m]=k.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('en-PK',{month:'short',year:'numeric'})}
function expenseGroups(rows){const g={};rows.forEach(e=>{const k=e.category||'Other';g[k]=(g[k]||0)+N(e.amount)});return Object.entries(g).sort((a,b)=>b[1]-a[1])}
function ensureTaxPanel(){const reports=$('#reportsView');if(!reports)return null;let p=$('#v14TaxPanel');if(p)return p;p=document.createElement('div');p.id='v14TaxPanel';p.className='panel';p.innerHTML=`<div class="panel-head"><div><span class="section-kicker">FBR / TAX WORKING</span><h3>Annual Business Summary</h3></div></div><p class="muted">Normal Pakistan tax year working summary: 1 July to 30 June. This is a business working report; final tax treatment/adjustments should be checked before filing.</p><div class="v14-tax-toolbar"><label class="field"><span>Tax Year</span><select id="v14TaxYear"></select></label><button type="button" class="ghost" id="v14PrintTax">Print Summary</button><button type="button" class="ghost" id="v14ExportTax">Export CSV</button></div><div id="v14TaxContent"></div>`;reports.appendChild(p);const sel=p.querySelector('#v14TaxYear'),cy=currentTaxYear();for(let y=cy;y>=cy-6;y--){const o=document.createElement('option');o.value=y;o.textContent=`Tax Year ${y} — Jul ${y-1} to Jun ${y}${y===cy?' (Current)':''}`;sel.appendChild(o)}sel.value=String(cy);sel.addEventListener('change',()=>renderTax(true));p.querySelector('#v14PrintTax').onclick=printTax;p.querySelector('#v14ExportTax').onclick=exportTax;return p}
let taxSig='';
function renderTax(force=false){const p=ensureTaxPanel();if(!p)return;const y=N($('#v14TaxYear')?.value)||currentTaxYear(),[from,to]=taxBounds(y),db=read(),m=metrics(db,from,to),sig=JSON.stringify([y,m.sales,m.received,m.receivable,m.direct,m.gross,m.expenses,m.net,m.vendorCost,m.vendorPaid,m.vendorPayable,m.orders.length,m.expensesRows.length]);if(!force&&sig===taxSig)return;taxSig=sig;const months=monthKeys(y),rows=months.map(k=>{const a=k+'-01',d=new Date(Number(k.slice(0,4)),Number(k.slice(5,7)),0),b=D(d),x=metrics(db,a,b);return`<tr><td>${E(monthLabel(k))}</td><td>${R(x.sales)}</td><td>${R(x.direct)}</td><td>${R(x.gross)}</td><td>${R(x.expenses)}</td><td>${R(x.net)}</td><td>${R(x.received)}</td><td>${R(x.receivable)}</td></tr>`}).join(''),eg=expenseGroups(m.expensesRows);$('#v14TaxContent').innerHTML=`<div class="v14-tax-grid"><div class="v14-tax-box"><span>Business Sales / Turnover</span><b>${R(m.sales)}</b></div><div class="v14-tax-box"><span>Direct Production Cost</span><b>${R(m.direct)}</b></div><div class="v14-tax-box"><span>Gross Profit</span><b>${R(m.gross)}</b></div><div class="v14-tax-box"><span>Operating / Office Expenses</span><b>${R(m.expenses)}</b></div><div class="v14-tax-box"><span>Net Business Profit</span><b>${R(m.net)}</b></div><div class="v14-tax-box"><span>Customer Received</span><b>${R(m.received)}</b></div><div class="v14-tax-box"><span>Customer Receivable</span><b>${R(m.receivable)}</b></div><div class="v14-tax-box"><span>Vendor Payable</span><b>${R(m.vendorPayable)}</b></div></div><div class="v14-note">Period: <b>${from}</b> to <b>${to}</b> • Orders: <b>${m.orders.length}</b> • Vendor payments during period: <b>${R(m.vendorPaid)}</b></div><div class="v14-table"><table><thead><tr><th>Month</th><th>Sales</th><th>Direct Cost</th><th>Gross Profit</th><th>Expenses</th><th>Net Profit</th><th>Received</th><th>Receivable</th></tr></thead><tbody>${rows}</tbody></table></div><div class="panel-head" style="margin-top:16px"><div><span class="section-kicker">EXPENSE CLASSIFICATION</span><h3>Expense Categories</h3></div></div><div class="v14-expenses">${eg.length?eg.map(([k,v])=>`<div class="v14-exp-row"><span>${E(k)}</span><b>${R(v)}</b></div>`).join(''):'<div class="empty">No expenses in this tax year.</div>'}</div>`;
}
function taxData(){const y=N($('#v14TaxYear')?.value)||currentTaxYear(),[from,to]=taxBounds(y),db=read(),m=metrics(db,from,to);return{y,from,to,db,m}}
function printTax(){const {y,from,to,m}=taxData(),w=open('','_blank');if(!w)return;const eg=expenseGroups(m.expensesRows),months=monthKeys(y),mr=months.map(k=>{const a=k+'-01',d=new Date(Number(k.slice(0,4)),Number(k.slice(5,7)),0),b=D(d),x=metrics(read(),a,b);return`<tr><td>${E(monthLabel(k))}</td><td>${R(x.sales)}</td><td>${R(x.direct)}</td><td>${R(x.gross)}</td><td>${R(x.expenses)}</td><td>${R(x.net)}</td></tr>`}).join('');w.document.write(`<!doctype html><html><head><title>Tax Year ${y} Business Summary</title><style>@page{size:A4;margin:12mm}body{font-family:Arial;color:#161616}h1{margin:0;color:#d71920}.muted{color:#666;font-size:11px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:14px 0}.box{border:1px solid #ddd;padding:9px;border-radius:7px}.box span{font-size:9px;color:#666}.box b{display:block;font-size:16px;margin-top:4px}table{width:100%;border-collapse:collapse;margin:12px 0}th,td{border:1px solid #ddd;padding:6px;font-size:9px;text-align:left}th{background:#17191d;color:#fff}</style></head><body><h1>Design Line Agency</h1><h2>Tax Year ${y} — Business Working Summary</h2><div class="muted">${from} to ${to} • Working report for return preparation</div><div class="grid"><div class="box"><span>Sales / Turnover</span><b>${R(m.sales)}</b></div><div class="box"><span>Direct Cost</span><b>${R(m.direct)}</b></div><div class="box"><span>Gross Profit</span><b>${R(m.gross)}</b></div><div class="box"><span>Expenses</span><b>${R(m.expenses)}</b></div><div class="box"><span>Net Business Profit</span><b>${R(m.net)}</b></div><div class="box"><span>Receivable</span><b>${R(m.receivable)}</b></div></div><h3>Monthly Summary</h3><table><thead><tr><th>Month</th><th>Sales</th><th>Direct Cost</th><th>Gross Profit</th><th>Expenses</th><th>Net Profit</th></tr></thead><tbody>${mr}</tbody></table><h3>Expense Categories</h3><table><tbody>${eg.map(([k,v])=>`<tr><td>${E(k)}</td><td>${R(v)}</td></tr>`).join('')||'<tr><td>No expenses</td><td>Rs 0</td></tr>'}</tbody></table><div class="muted">Note: This is an internal business working summary. Verify tax adjustments, admissibility and filing treatment before submitting the return.</div><script>window.onload=()=>print()<\/script></body></html>`);w.document.close()}
function exportTax(){const {y,from,to,m}=taxData(),rows=[['Design Line Agency','Tax Year '+y],['Period',from+' to '+to],[],['Metric','Amount'],['Sales / Turnover',m.sales],['Direct Production Cost',m.direct],['Gross Profit',m.gross],['Office / Other Expenses',m.expenses],['Net Business Profit',m.net],['Customer Received',m.received],['Customer Receivable',m.receivable],['Vendor Paid',m.vendorPaid],['Vendor Payable',m.vendorPayable],[],['Expense Category','Amount'],...expenseGroups(m.expensesRows)];const csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`DesignLine_TaxYear_${y}_Summary.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function reportBounds(){const t=$('#reportRange')?.value||'month',n=new Date(),today=D();if(t==='all')return['0000-01-01','9999-12-31'];if(t==='today')return[today,today];if(t==='week'){const s=new Date(n);s.setDate(n.getDate()-((n.getDay()+6)%7));return[D(s),today]}if(t==='month')return[`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-01`,today];if(t==='year')return[`${n.getFullYear()}-01-01`,`${n.getFullYear()}-12-31`];return[$('#v7From')?.value||today,$('#v7To')?.value||today]}
let reportSig='';
function patchReports(force=false){if(!$('#reportsView')?.classList.contains('active'))return;const db=read(),[from,to]=reportBounds(),m=metrics(db,from,to),sig=JSON.stringify([from,to,m.sales,m.received,m.receivable,m.direct,m.gross,m.expenses,m.net,m.vendorPaid,m.vendorPayable]);if(!force&&sig===reportSig&&$('#reportCards')?.dataset.v14==='1'){renderTax();return}reportSig=sig;const box=$('#reportCards');if(box){box.dataset.v14='1';box.innerHTML=card('Sales',m.sales,`${from} to ${to}`)+card('Received',m.received,`${from} to ${to}`)+card('Customer Receivable',m.receivable,`${from} to ${to}`)+card('Direct / Production Cost',m.direct,`${from} to ${to}`)+card('Gross Profit',m.gross,'Sales − direct cost')+card('Office / Other Expenses',m.expenses,`${from} to ${to}`)+card('Net Profit',m.net,'Gross profit − expenses')+card('Vendor Payable',m.vendorPayable,`Paid ${R(m.vendorPaid)}`)}renderTax(force)}
let timer=null;function schedule(force=false){clearTimeout(timer);timer=setTimeout(()=>{injectStyle();renderDashboard(force);patchReports(force)},50)}
function init(){injectStyle();renderDashboard(true);ensureTaxPanel();document.addEventListener('click',e=>{if(e.target.closest?.('[data-view="dashboard"],[data-jump="dashboard"]'))setTimeout(()=>renderDashboard(true),20);if(e.target.closest?.('[data-view="reports"],[data-jump="reports"]'))setTimeout(()=>patchReports(true),30)},true);document.addEventListener('change',e=>{if(['reportRange','v7From','v7To','v14TaxYear'].includes(e.target?.id))schedule(true)},true);new MutationObserver(ms=>{if(ms.every(m=>m.target?.closest?.('#dashboardCards,#v14FinancePanel,#reportCards,#v14TaxPanel')))return;schedule(false)}).observe(document.body,{childList:true,subtree:true});setInterval(()=>schedule(false),2500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();