(()=>{'use strict';
const K='designlineERP_v2',$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const N=x=>Number(x)||0,R=x=>'Rs '+N(x).toLocaleString('en-PK'),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const D=(d=new Date())=>{const p=x=>String(x).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const read=()=>{try{return JSON.parse(localStorage.getItem(K))||{}}catch(e){return{}}};
const lines=o=>(o?.lineItems||[]).length?o.lineItems:[o||{}];
const flex=x=>['Flex Printing','Wallpaper + Fitting'].includes(x?.service);
const area=x=>N(x.widthFt)&&N(x.heightFt)?N(x.widthFt)*N(x.heightFt)*Math.max(1,N(x.panels)||1):N(x.qty);
function lineSale(x){const s=x?.service||'Other';if(flex(x))return area(x)*N(x.rate)+N(x.designCharges)+N(x.fittingCharges)+N(x.otherCharges);if(s==='Passport Photos')return N(x.qty)*N(x.rate)+N(x.retouchCharges)+N(x.otherCharges);if(s==='ID / Document Print')return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.laminationCharges)+N(x.otherCharges);return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.finishingCharges)+N(x.fittingCharges)+N(x.otherCharges)}
function lineVendorExpense(x){if(x?.service==='Offset / Packaging')return N(x.printingCost)+N(x.plateQty)*N(x.plateRate)+N(x.dieCost)+N(x.laminationCost)+N(x.uvFoilCost)+N(x.cuttingCost)+N(x.bindingCost)+N(x.packingCost)+N(x.transportCost)+N(x.vendorCost);return N(x?.vendorCost)}
const orderSale=o=>lines(o).reduce((a,l)=>a+lineSale(l),0);
const orderVendorExpense=o=>lines(o).reduce((a,l)=>a+lineVendorExpense(l),0);
const orderPaid=(db,o)=>N(o.advance)+(db.payments||[]).filter(p=>p.orderId===o.id).reduce((a,p)=>a+N(p.amount),0);
const within=(d,a,b)=>d&&d>=a&&d<=b;
function vendorLedgerCost(db,from='0000-01-01',to='9999-12-31'){let t=0;(db.orders||[]).filter(o=>o.status!=='Cancelled'&&within(o.date,from,to)).forEach(o=>lines(o).forEach(l=>{if(l.vendorId)t+=N(l.vendorCost)}));return t}
function metrics(db,from='0000-01-01',to='9999-12-31'){
 const os=(db.orders||[]).filter(o=>o.status!=='Cancelled'&&within(o.date,from,to));
 const es=(db.expenses||[]).filter(e=>within(e.date,from,to));
 const vps=(db.vendorPayments||[]).filter(p=>within(p.date,from,to));
 const sales=os.reduce((a,o)=>a+orderSale(o),0),received=os.reduce((a,o)=>a+orderPaid(db,o),0),receivable=os.reduce((a,o)=>a+Math.max(0,orderSale(o)-orderPaid(db,o)),0),vendorExpense=os.reduce((a,o)=>a+orderVendorExpense(o),0),otherExpense=es.reduce((a,e)=>a+N(e.amount),0),net=sales-vendorExpense-otherExpense,vendorPaid=vps.reduce((a,p)=>a+N(p.amount),0),vendorCost=vendorLedgerCost(db,from,to),vendorPayable=Math.max(0,vendorCost-vendorPaid);
 return{orders:os,expensesRows:es,vendorPayments:vps,sales,received,receivable,vendorExpense,otherExpense,net,vendorPaid,vendorCost,vendorPayable};
}
function card(label,value,foot,accent=''){return `<div class="stat-card v15-card"${accent?` style="--accent:${accent}"`:''}><div class="stat-top"><span class="stat-label">${E(label)}</span></div><strong class="stat-value">${R(value)}</strong><div class="stat-foot">${E(foot||'')}</div></div>`}
function injectStyle(){if($('#acctV15Style'))return;const s=document.createElement('style');s.id='acctV15Style';s.textContent=`
#dashboardCards.v15-dashboard{grid-template-columns:repeat(4,minmax(0,1fr))}.v15-card .stat-value{font-size:23px}.v15-finance{margin:14px 0}.v15-equation{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.v15-equation>div{padding:12px;border:1px solid var(--line);border-radius:12px;background:var(--surface-2)}.v15-equation span{display:block;color:var(--muted);font-size:10px;font-weight:800;text-transform:uppercase}.v15-equation b{display:block;font-size:17px;margin-top:6px}.v15-note{margin-top:10px;font-size:11px;color:var(--muted);line-height:1.55}.v15-tax-toolbar{display:flex;gap:9px;align-items:end;flex-wrap:wrap;margin:12px 0}.v15-tax-toolbar label{min-width:210px}.v15-tax-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:12px 0}.v15-tax-box{padding:12px;border:1px solid var(--line);border-radius:12px;background:var(--surface-2)}.v15-tax-box span{display:block;font-size:10px;color:var(--muted);font-weight:800}.v15-tax-box b{display:block;font-size:19px;margin-top:5px}.v15-table{overflow:auto;border:1px solid var(--line);border-radius:12px;margin-top:12px}.v15-table table{min-width:720px}.v15-table th,.v15-table td{white-space:nowrap}.v15-expenses{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px 14px;margin-top:10px}.v15-exp-row{display:flex;justify-content:space-between;gap:12px;border-bottom:1px dashed var(--line);padding:6px 0;font-size:11px}@media(max-width:1000px){#dashboardCards.v15-dashboard,.v15-tax-grid,.v15-equation{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){#dashboardCards.v15-dashboard,.v15-tax-grid,.v15-equation,.v15-expenses{grid-template-columns:1fr}.v15-card .stat-value{font-size:20px}}
`;document.head.appendChild(s)}
let dashSig='';
function renderDashboard(force=false){const box=$('#dashboardCards');if(!box)return;const db=read(),m=metrics(db),sig=JSON.stringify([m.sales,m.received,m.receivable,m.vendorExpense,m.otherExpense,m.net,m.vendorPaid,m.vendorPayable,m.orders.length]);if(!force&&sig===dashSig&&box.dataset.v15==='1')return;dashSig=sig;box.dataset.v15='1';box.classList.add('v15-dashboard');box.innerHTML=card('Total Sales',m.sales,`${m.orders.length} active orders`,'#3077d5')+card('Received',m.received,'Customer collections received','#14945c')+card('Customer Receivable',m.receivable,'Still to collect from customers','#e31b23')+card('Vendor / Production Expense',m.vendorExpense,'Job cost to vendors / production','#d98324')+card('Other Expenses',m.otherExpense,'Office, material, fuel, salary, utilities etc.','#b95d2a')+card('Net Profit',m.net,'Sales − vendor expense − other expenses','#14945c')+card('Vendor Paid',m.vendorPaid,'Payments already made to vendors','#7457d9')+card('Vendor Payable',m.vendorPayable,'Vendor bills still unpaid','#e31b23');
 let p=$('#v15FinancePanel');if(!p){p=document.createElement('div');p.id='v15FinancePanel';p.className='panel v15-finance';box.insertAdjacentElement('afterend',p)}p.innerHTML=`<div class="panel-head"><div><span class="section-kicker">NET PROFIT STRUCTURE</span><h3>Business Profit Calculation</h3></div></div><div class="v15-equation"><div><span>Total Sales</span><b>${R(m.sales)}</b></div><div><span>Less: Vendor / Production Expense</span><b>${R(m.vendorExpense)}</b></div><div><span>Less: Other Expenses</span><b>${R(m.otherExpense)}</b></div><div><span>Net Profit</span><b>${R(m.net)}</b></div></div><div class="v15-note"><b>Formula:</b> Total Sales − Vendor / Production Expense − Other Expenses = Net Profit. Vendor expense profit se us waqt minus hota hai jab job cost record hoti hai, chahe vendor ko payment abhi hui ho ya payable ho. Vendor Paid aur Vendor Payable sirf payment status dikhate hain.</div>`;
}
function reportBounds(){const t=$('#reportRange')?.value||'month',n=new Date(),today=D();if(t==='all')return['0000-01-01','9999-12-31'];if(t==='today')return[today,today];if(t==='week'){const s=new Date(n);s.setDate(n.getDate()-((n.getDay()+6)%7));return[D(s),today]}if(t==='month')return[`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-01`,today];if(t==='year')return[`${n.getFullYear()}-01-01`,`${n.getFullYear()}-12-31`];return[$('#v7From')?.value||today,$('#v7To')?.value||today]}
let reportSig='';
function renderReports(force=false){if(!$('#reportsView')?.classList.contains('active'))return;const [from,to]=reportBounds(),db=read(),m=metrics(db,from,to),box=$('#reportCards');if(!box)return;const sig=JSON.stringify([from,to,m.sales,m.received,m.receivable,m.vendorExpense,m.otherExpense,m.net,m.vendorPaid,m.vendorPayable]);if(force||sig!==reportSig||box.dataset.v15!=='1'){reportSig=sig;box.dataset.v15='1';box.innerHTML=card('Sales',m.sales,`${from} to ${to}`)+card('Received',m.received,`${from} to ${to}`)+card('Customer Pending',m.receivable,`${from} to ${to}`)+card('Vendor / Production Expense',m.vendorExpense,`${from} to ${to}`)+card('Other Expenses',m.otherExpense,`${from} to ${to}`)+card('Net Profit',m.net,'Sales − vendor expense − other expenses')+card('Vendor Paid',m.vendorPaid,`${from} to ${to}`)+card('Vendor Payable',m.vendorPayable,'Selected-period vendor balance')}
 for(const tr of $$('#v7Breakdown tr')){const td=tr.querySelectorAll('td');if(td.length<8)continue;const money=i=>N((td[i].textContent||'').replace(/[^0-9.-]/g,''));td[7].textContent=R(money(1)-money(4)-money(6))}
}
function currentTaxYear(){const n=new Date();return n.getMonth()>=6?n.getFullYear()+1:n.getFullYear()}
function taxBounds(y){return[`${y-1}-07-01`,`${y}-06-30`]}
function monthKeys(y){const out=[];for(let m=7;m<=12;m++)out.push(`${y-1}-${String(m).padStart(2,'0')}`);for(let m=1;m<=6;m++)out.push(`${y}-${String(m).padStart(2,'0')}`);return out}
function monthLabel(k){const [y,m]=k.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('en-PK',{month:'short',year:'numeric'})}
function expenseGroups(rows){const g={};rows.forEach(e=>{const k=e.category||'Other';g[k]=(g[k]||0)+N(e.amount)});return Object.entries(g).sort((a,b)=>b[1]-a[1])}
function ensureTaxPanel(){const reports=$('#reportsView');if(!reports)return null;let p=$('#v15TaxPanel');if(p)return p;const old=$('#v14TaxPanel');if(old)old.remove();p=document.createElement('div');p.id='v15TaxPanel';p.className='panel';p.innerHTML=`<div class="panel-head"><div><span class="section-kicker">FBR / TAX WORKING</span><h3>Annual Business Summary</h3></div></div><p class="muted">Tax working summary ke liye sales, vendor/production expense, doosre expenses aur net profit ko alag rakha gaya hai. Final filing se pehle tax treatment apne tax adviser se verify karein.</p><div class="v15-tax-toolbar"><label class="field"><span>Tax Year</span><select id="v15TaxYear"></select></label><button type="button" class="ghost" id="v15PrintTax">Print Summary</button><button type="button" class="ghost" id="v15ExportTax">Export CSV</button></div><div id="v15TaxContent"></div>`;reports.appendChild(p);const sel=p.querySelector('#v15TaxYear'),cy=currentTaxYear();for(let y=cy;y>=cy-6;y--){const o=document.createElement('option');o.value=y;o.textContent=`Tax Year ${y} — Jul ${y-1} to Jun ${y}${y===cy?' (Current)':''}`;sel.appendChild(o)}sel.value=String(cy);sel.addEventListener('change',()=>renderTax(true));p.querySelector('#v15PrintTax').onclick=printTax;p.querySelector('#v15ExportTax').onclick=exportTax;return p}
let taxSig='';
function renderTax(force=false){const p=ensureTaxPanel();if(!p)return;const y=N($('#v15TaxYear')?.value)||currentTaxYear(),[from,to]=taxBounds(y),db=read(),m=metrics(db,from,to),sig=JSON.stringify([y,m.sales,m.vendorExpense,m.otherExpense,m.net,m.received,m.receivable,m.vendorPaid,m.vendorPayable,m.orders.length]);if(!force&&sig===taxSig)return;taxSig=sig;const rows=monthKeys(y).map(k=>{const a=k+'-01',d=new Date(Number(k.slice(0,4)),Number(k.slice(5,7)),0),b=D(d),x=metrics(db,a,b);return`<tr><td>${E(monthLabel(k))}</td><td>${R(x.sales)}</td><td>${R(x.vendorExpense)}</td><td>${R(x.otherExpense)}</td><td>${R(x.net)}</td><td>${R(x.received)}</td><td>${R(x.receivable)}</td></tr>`}).join(''),eg=expenseGroups(m.expensesRows);$('#v15TaxContent').innerHTML=`<div class="v15-tax-grid"><div class="v15-tax-box"><span>Business Sales / Turnover</span><b>${R(m.sales)}</b></div><div class="v15-tax-box"><span>Vendor / Production Expense</span><b>${R(m.vendorExpense)}</b></div><div class="v15-tax-box"><span>Other / Office Expenses</span><b>${R(m.otherExpense)}</b></div><div class="v15-tax-box"><span>Net Business Profit</span><b>${R(m.net)}</b></div><div class="v15-tax-box"><span>Customer Received</span><b>${R(m.received)}</b></div><div class="v15-tax-box"><span>Customer Receivable</span><b>${R(m.receivable)}</b></div><div class="v15-tax-box"><span>Vendor Paid</span><b>${R(m.vendorPaid)}</b></div><div class="v15-tax-box"><span>Vendor Payable</span><b>${R(m.vendorPayable)}</b></div></div><div class="v15-note">Period: <b>${from}</b> to <b>${to}</b> • Formula: <b>Sales − Vendor/Production Expense − Other Expenses = Net Profit</b></div><div class="v15-table"><table><thead><tr><th>Month</th><th>Sales</th><th>Vendor / Production Expense</th><th>Other Expenses</th><th>Net Profit</th><th>Received</th><th>Receivable</th></tr></thead><tbody>${rows}</tbody></table></div><div class="panel-head" style="margin-top:16px"><div><span class="section-kicker">EXPENSE CLASSIFICATION</span><h3>Other Expense Categories</h3></div></div><div class="v15-expenses">${eg.length?eg.map(([k,v])=>`<div class="v15-exp-row"><span>${E(k)}</span><b>${R(v)}</b></div>`).join(''):'<div class="empty">No other expenses in this tax year.</div>'}</div>`}
function taxData(){const y=N($('#v15TaxYear')?.value)||currentTaxYear(),[from,to]=taxBounds(y),db=read(),m=metrics(db,from,to);return{y,from,to,db,m}}
function printTax(){const {y,from,to,db,m}=taxData(),w=open('','_blank');if(!w)return;const rows=monthKeys(y).map(k=>{const a=k+'-01',d=new Date(Number(k.slice(0,4)),Number(k.slice(5,7)),0),b=D(d),x=metrics(db,a,b);return`<tr><td>${E(monthLabel(k))}</td><td>${R(x.sales)}</td><td>${R(x.vendorExpense)}</td><td>${R(x.otherExpense)}</td><td>${R(x.net)}</td></tr>`}).join('');w.document.write(`<!doctype html><html><head><title>Tax Year ${y} Business Summary</title><style>@page{size:A4;margin:12mm}body{font-family:Arial;color:#161616}h1{color:#d71920;margin:0}.muted{font-size:11px;color:#666}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:14px 0}.box{border:1px solid #ddd;padding:9px;border-radius:7px}.box span{font-size:9px;color:#666}.box b{display:block;font-size:15px;margin-top:5px}table{width:100%;border-collapse:collapse;margin-top:14px}th,td{border:1px solid #ddd;padding:7px;font-size:9px;text-align:left}th{background:#17191d;color:#fff}</style></head><body><h1>Design Line Agency</h1><div class="muted">Tax Year ${y} Business Working Summary • ${from} to ${to}</div><div class="grid"><div class="box"><span>Sales</span><b>${R(m.sales)}</b></div><div class="box"><span>Vendor / Production Expense</span><b>${R(m.vendorExpense)}</b></div><div class="box"><span>Other Expenses</span><b>${R(m.otherExpense)}</b></div><div class="box"><span>Net Profit</span><b>${R(m.net)}</b></div></div><div class="muted">Net Profit = Sales − Vendor / Production Expense − Other Expenses. This is a business working summary; final tax treatment should be verified before filing.</div><table><thead><tr><th>Month</th><th>Sales</th><th>Vendor / Production Expense</th><th>Other Expenses</th><th>Net Profit</th></tr></thead><tbody>${rows}</tbody></table><script>window.onload=()=>print()<\/script></body></html>`);w.document.close()}
function exportTax(){const {y,db}=taxData(),rows=[['Tax Year','Month','Sales','Vendor / Production Expense','Other Expenses','Net Profit','Received','Receivable']];for(const k of monthKeys(y)){const a=k+'-01',d=new Date(Number(k.slice(0,4)),Number(k.slice(5,7)),0),b=D(d),x=metrics(db,a,b);rows.push([y,monthLabel(k),x.sales,x.vendorExpense,x.otherExpense,x.net,x.received,x.receivable])}const csv=rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`DesignLine_Tax_Year_${y}_Working.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
let timer=null,busy=false;function patch(force=false){clearTimeout(timer);timer=setTimeout(()=>{if(busy)return;busy=true;try{injectStyle();renderDashboard(force);renderReports(force);if($('#reportsView')?.classList.contains('active'))renderTax(force)}finally{busy=false}},50)}
function init(){injectStyle();patch(true);document.addEventListener('change',e=>{if(['reportRange','v7From','v7To','v15TaxYear'].includes(e.target?.id))patch(true)},true);document.addEventListener('click',e=>{if(e.target.closest?.('.nav-btn[data-view="dashboard"],.nav-btn[data-view="reports"],[data-jump="dashboard"],[data-jump="reports"]'))setTimeout(()=>patch(true),80)},true);new MutationObserver(muts=>{if(muts.every(m=>m.target?.closest?.('#dashboardCards,#v15FinancePanel,#reportCards,#v15TaxPanel')))return;patch(false)}).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();