(()=>{'use strict';
const K='designlineERP_v2',$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],N=x=>Number(x)||0,R=x=>'Rs '+N(x).toLocaleString('en-PK');
const D=(d=new Date())=>{const p=x=>String(x).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
function read(){try{return JSON.parse(localStorage.getItem(K))||{}}catch(e){return{}}}
function lines(o){return (o?.lineItems||[]).length?o.lineItems:[o||{}]}
function area(x){return N(x.widthFt)&&N(x.heightFt)?N(x.widthFt)*N(x.heightFt)*Math.max(1,N(x.panels)||1):N(x.qty)}
function lineTotal(x){const s=x?.service||'Other';if(s==='Flex Printing'||s==='Wallpaper + Fitting')return area(x)*N(x.rate)+N(x.designCharges)+N(x.fittingCharges)+N(x.otherCharges);if(s==='Passport Photos')return N(x.qty)*N(x.rate)+N(x.retouchCharges)+N(x.otherCharges);if(s==='ID / Document Print')return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.laminationCharges)+N(x.otherCharges);return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.finishingCharges)+N(x.fittingCharges)+N(x.otherCharges)}
function orderTotal(o){return lines(o).reduce((a,l)=>a+lineTotal(l),0)}
function orderPaid(db,o){return N(o.advance)+(db.payments||[]).filter(p=>p.orderId===o.id).reduce((a,p)=>a+N(p.amount),0)}
function bounds(){const t=$('#reportRange')?.value||'month',n=new Date(),today=D();if(t==='all')return['0000-01-01','9999-12-31'];if(t==='today')return[today,today];if(t==='week'){const s=new Date(n);s.setDate(n.getDate()-((n.getDay()+6)%7));return[D(s),today]}if(t==='month')return[`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-01`,today];if(t==='year')return[`${n.getFullYear()}-01-01`,`${n.getFullYear()}-12-31`];return[$('#v7From')?.value||today,$('#v7To')?.value||today]}
const within=(d,a,b)=>d&&d>=a&&d<=b;
function setCard(card,label,value,foot){if(!card)return;const l=card.querySelector('.stat-label'),v=card.querySelector('.stat-value'),f=card.querySelector('.stat-foot');if(l)l.textContent=label;if(v)v.textContent=R(value);if(f&&foot!==undefined)f.textContent=foot}
function patchDashboard(){const db=read(),cards=$$('#dashboardCards .stat-card');if(cards.length<4)return;const orders=(db.orders||[]).filter(o=>o.status!=='Cancelled'),sales=orders.reduce((a,o)=>a+orderTotal(o),0),received=orders.reduce((a,o)=>a+orderPaid(db,o),0),pending=orders.reduce((a,o)=>a+Math.max(0,orderTotal(o)-orderPaid(db,o)),0),vp=(db.vendorPayments||[]).reduce((a,p)=>a+N(p.amount),0),exp=(db.expenses||[]).reduce((a,e)=>a+N(e.amount),0),net=sales-vp-exp;
setCard(cards[0],'Total Sales',sales,`${orders.length} orders`);setCard(cards[1],'Received',received,'Customer collections');setCard(cards[2],'Pending Bills',pending,`${orders.filter(o=>Math.max(0,orderTotal(o)-orderPaid(db,o))>0).length} orders`);setCard(cards[3],'Net Profit',net,`Sales − Vendor Paid ${R(vp)} − Expenses ${R(exp)}`)}
function patchReports(){if(!$('#reportsView')?.classList.contains('active'))return;const db=read(),[a,b]=bounds(),orders=(db.orders||[]).filter(o=>o.status!=='Cancelled'&&within(o.date,a,b)),vps=(db.vendorPayments||[]).filter(p=>within(p.date,a,b)),exps=(db.expenses||[]).filter(e=>within(e.date,a,b)),sales=orders.reduce((s,o)=>s+orderTotal(o),0),received=orders.reduce((s,o)=>s+orderPaid(db,o),0),pending=orders.reduce((s,o)=>s+Math.max(0,orderTotal(o)-orderPaid(db,o)),0),vp=vps.reduce((s,p)=>s+N(p.amount),0),exp=exps.reduce((s,e)=>s+N(e.amount),0),gross=sales-vp,net=gross-exp;
const cards=$$('#reportCards .stat-card');for(const c of cards){const label=(c.querySelector('.stat-label')?.textContent||'').trim().toLowerCase();if(label==='sales')setCard(c,'Sales',sales,`${a} to ${b}`);else if(label==='received')setCard(c,'Received',received,`${a} to ${b}`);else if(label==='customer pending')setCard(c,'Customer Pending',pending,`${a} to ${b}`);else if(label==='vendor payments')setCard(c,'Vendor Payments',vp,`${a} to ${b}`);else if(label==='expenses')setCard(c,'Expenses',exp,`${a} to ${b}`);else if(label==='gross profit')setCard(c,'Gross Profit',gross,`Sales − Vendor Payments • ${a} to ${b}`);else if(label==='net profit')setCard(c,'Net Profit',net,`Gross Profit − Expenses • ${a} to ${b}`)}
const rows=$$('#v7Breakdown tr');for(const tr of rows){const td=tr.querySelectorAll('td');if(td.length<8)continue;const key=td[0].textContent.trim();let ra,rb;if(/^\d{4}-\d{2}$/.test(key)){ra=key+'-01';const d=new Date(Number(key.slice(0,4)),Number(key.slice(5,7)),0);rb=D(d)}else{ra=rb=key}const sv=(db.orders||[]).filter(o=>o.status!=='Cancelled'&&within(o.date,ra,rb)).reduce((s,o)=>s+orderTotal(o),0),vv=(db.vendorPayments||[]).filter(p=>within(p.date,ra,rb)).reduce((s,p)=>s+N(p.amount),0),ee=(db.expenses||[]).filter(e=>within(e.date,ra,rb)).reduce((s,e)=>s+N(e.amount),0);td[7].textContent=R(sv-vv-ee)}}
let busy=false;function patch(){if(busy)return;busy=true;setTimeout(()=>{patchDashboard();patchReports();busy=false},30)}
function init(){patch();document.addEventListener('change',e=>{if(e.target?.id==='reportRange'||e.target?.id==='v7From'||e.target?.id==='v7To')setTimeout(patch,50)},true);new MutationObserver(patch).observe(document.body,{childList:true,subtree:true,characterData:true});setInterval(patch,1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();