(()=>{'use strict';
const K='designlineERP_v2',$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const N=x=>Number(x)||0,R=x=>'Rs '+N(x).toLocaleString('en-PK'),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const D=(d=new Date())=>{const p=x=>String(x).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`};
const read=()=>{try{return JSON.parse(localStorage.getItem(K))||{}}catch(e){return{}}};
const lines=o=>(o?.lineItems||[]).length?o.lineItems:[o||{}];
const flex=x=>['Flex Printing','Wallpaper + Fitting'].includes(x?.service);
const area=x=>N(x.widthFt)&&N(x.heightFt)?N(x.widthFt)*N(x.heightFt)*Math.max(1,N(x.panels)||1):N(x.qty);
function lineSale(x){const ex=N(x.otherCharges)+N(x.otherCharges2)+N(x.otherCharges3),s=x?.service||'Other';if(flex(x))return area(x)*N(x.rate)+N(x.designCharges)+N(x.fittingCharges)+ex;if(s==='Passport Photos')return N(x.qty)*N(x.rate)+N(x.retouchCharges)+ex;if(s==='ID / Document Print')return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.laminationCharges)+ex;return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.finishingCharges)+N(x.fittingCharges)+ex}
const orderSale=o=>Math.max(0,lines(o).reduce((a,l)=>a+lineSale(l),0)-N(o.discount));
const orderPaid=(db,o)=>N(o.advance)+(db.payments||[]).filter(p=>p.orderId===o.id).reduce((a,p)=>a+N(p.amount),0);
const within=(d,a,b)=>d&&d>=a&&d<=b;
function metrics(db,from='0000-01-01',to='9999-12-31'){const os=(db.orders||[]).filter(o=>o.status!=='Cancelled'&&within(o.date,from,to)),vps=(db.vendorPayments||[]).filter(p=>within(p.date,from,to)),es=(db.expenses||[]).filter(e=>within(e.date,from,to));const sales=os.reduce((a,o)=>a+orderSale(o),0),received=os.reduce((a,o)=>a+orderPaid(db,o),0),pending=os.reduce((a,o)=>a+Math.max(0,orderSale(o)-orderPaid(db,o)),0),vendorPaid=vps.reduce((a,p)=>a+N(p.amount),0),expenses=es.reduce((a,e)=>a+N(e.amount),0),net=sales-vendorPaid-expenses;return{orders:os,vendorPayments:vps,expenseRows:es,sales,received,pending,vendorPaid,expenses,net}}
function reportBounds(){const t=$('#reportRange')?.value||'month',n=new Date(),today=D();if(t==='all')return['0000-01-01','9999-12-31'];if(t==='today')return[today,today];if(t==='week'){const s=new Date(n);s.setDate(n.getDate()-((n.getDay()+6)%7));return[D(s),today]}if(t==='month')return[`${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-01`,today];if(t==='year')return[`${n.getFullYear()}-01-01`,`${n.getFullYear()}-12-31`];return[$('#v7From')?.value||today,$('#v7To')?.value||today]}
function card(label,value,foot,accent=''){return `<div class="stat-card acct17-card"${accent?` style="--accent:${accent}"`:''}><div class="stat-top"><span class="stat-label">${E(label)}</span></div><strong class="stat-value">${R(value)}</strong><div class="stat-foot">${E(foot||'')}</div></div>`}
function injectStyle(){if($('#acct17Style'))return;const s=document.createElement('style');s.id='acct17Style';s.textContent='#reportCards.acct17-report{grid-template-columns:repeat(3,minmax(0,1fr))!important}.acct17-tax-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin:12px 0}.acct17-tax-box{padding:12px;border:1px solid var(--line);border-radius:12px;background:var(--surface-2)}.acct17-tax-box span{display:block;font-size:10px;color:var(--muted);font-weight:800}.acct17-tax-box b{display:block;font-size:18px;margin-top:5px}.acct17-tax-toolbar{display:flex;gap:9px;align-items:end;flex-wrap:wrap;margin:12px 0}.acct17-tax-toolbar label{min-width:210px}.acct17-table{overflow:auto;border:1px solid var(--line);border-radius:12px;margin-top:12px}.acct17-table table{min-width:720px}.acct17-expenses{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px 14px;margin-top:10px}.acct17-exp-row{display:flex;justify-content:space-between;gap:12px;border-bottom:1px dashed var(--line);padding:6px 0;font-size:11px}@media(max-width:900px){#reportCards.acct17-report,.acct17-tax-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){#reportCards.acct17-report,.acct17-tax-grid,.acct17-expenses{grid-template-columns:1fr}}';document.head.appendChild(s)}
let reportSig='';
function renderReports(force=false){if(!$('#reportsView')?.classList.contains('active'))return;const [from,to]=reportBounds(),db=read(),m=metrics(db,from,to),box=$('#reportCards');if(!box)return;const sig=JSON.stringify([from,to,m.sales,m.received,m.pending,m.vendorPaid,m.expenses,m.net]);if(force||sig!==reportSig||box.dataset.acct17!=='1'){reportSig=sig;box.dataset.acct17='1';box.classList.add('acct17-report');box.innerHTML=card('Sales',m.sales,`${from} to ${to}`,'#3077d5')+card('Received',m.received,'Customer collections','#14945c')+card('Customer Pending',m.pending,'Still to collect','#e31b23')+card('Vendor Payments',m.vendorPaid,'Actually paid to vendors','#d98324')+card('Expenses',m.expenses,'Office / material / other expenses','#b95d2a')+card('Net Profit',m.net,'Sales − Vendor Payments − Expenses','#14945c')}
for(const tr of $$('#v7Breakdown tr')){const td=tr.querySelectorAll('td');if(td.length<8)continue;const money=i=>N((td[i].textContent||'').replace(/[^0-9.-]/g,''));td[7].textContent=R(money(1)-money(5)-money(6))}renderTax(false)}
function currentTaxYear(){const n=new Date();return n.getMonth()>=6?n.getFullYear()+1:n.getFullYear()}
function taxBounds(y){return[`${y-1}-07-01`,`${y}-06-30`]}
function monthKeys(y){const out=[];for(let m=7;m<=12;m++)out.push(`${y-1}-${String(m).padStart(2,'0')}`);for(let m=1;m<=6;m++)out.push(`${y}-${String(m).padStart(2,'0')}`);return out}
function monthLabel(k){const [y,m]=k.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('en-PK',{month:'short',year:'numeric'})}
function expenseGroups(rows){const g={};rows.forEach(e=>{const k=e.category||'Other';g[k]=(g[k]||0)+N(e.amount)});return Object.entries(g).sort((a,b)=>b[1]-a[1])}
function ensureTaxPanel(){const reports=$('#reportsView');if(!reports)return null;let p=$('#acct17TaxPanel');if(p)return p;$('#v15TaxPanel')?.remove();$('#v14TaxPanel')?.remove();p=document.createElement('div');p.id='acct17TaxPanel';p.className='panel';p.innerHTML=`<div class="panel-head"><div><span class="section-kicker">FBR / TAX WORKING</span><h3>Annual Business Summary</h3></div></div><p class="muted">Business working summary aapke current ERP method par hai: Sales − Vendor Payments − Expenses = Net Profit. Final FBR filing se pehle tax treatment apne tax adviser se verify karein.</p><div class="acct17-tax-toolbar"><label class="field"><span>Tax Year</span><select id="acct17TaxYear"></select></label><button type="button" class="ghost" id="acct17PrintTax">Print Summary</button><button type="button" class="ghost" id="acct17ExportTax">Export CSV</button></div><div id="acct17TaxContent"></div>`;reports.appendChild(p);const sel=p.querySelector('#acct17TaxYear'),cy=currentTaxYear();for(let y=cy;y>=cy-6;y--){const o=document.createElement('option');o.value=y;o.textContent=`Tax Year ${y} — Jul ${y-1} to Jun ${y}${y===cy?' (Current)':''}`;sel.appendChild(o)}sel.value=String(cy);sel.addEventListener('change',()=>renderTax(true));p.querySelector('#acct17PrintTax').onclick=printTax;p.querySelector('#acct17ExportTax').onclick=exportTax;return p}
let taxSig='';
function renderTax(force=false){const p=ensureTaxPanel();if(!p)return;const y=N($('#acct17TaxYear')?.value)||currentTaxYear(),[from,to]=taxBounds(y),db=read(),m=metrics(db,from,to),sig=JSON.stringify([y,m.sales,m.vendorPaid,m.expenses,m.net,m.received,m.pending]);if(!force&&sig===taxSig)return;taxSig=sig;const rows=monthKeys(y).map(k=>{const a=k+'-01',d=new Date(Number(k.slice(0,4)),Number(k.slice(5,7)),0),b=D(d),x=metrics(db,a,b);return`<tr><td>${E(monthLabel(k))}</td><td>${R(x.sales)}</td><td>${R(x.vendorPaid)}</td><td>${R(x.expenses)}</td><td>${R(x.net)}</td><td>${R(x.received)}</td><td>${R(x.pending)}</td></tr>`}).join(''),eg=expenseGroups(m.expenseRows);$('#acct17TaxContent').innerHTML=`<div class="acct17-tax-grid"><div class="acct17-tax-box"><span>Business Sales / Turnover</span><b>${R(m.sales)}</b></div><div class="acct17-tax-box"><span>Vendor Payments</span><b>${R(m.vendorPaid)}</b></div><div class="acct17-tax-box"><span>Other Expenses</span><b>${R(m.expenses)}</b></div><div class="acct17-tax-box"><span>Net Business Profit</span><b>${R(m.net)}</b></div><div class="acct17-tax-box"><span>Customer Received</span><b>${R(m.received)}</b></div><div class="acct17-tax-box"><span>Customer Pending</span><b>${R(m.pending)}</b></div></div><div class="acct17-table"><table><thead><tr><th>Month</th><th>Sales</th><th>Vendor Payments</th><th>Expenses</th><th>Net Profit</th><th>Received</th><th>Pending</th></tr></thead><tbody>${rows}</tbody></table></div><div class="panel-head" style="margin-top:16px"><div><span class="section-kicker">EXPENSE CLASSIFICATION</span><h3>Expense Categories</h3></div></div><div class="acct17-expenses">${eg.length?eg.map(([k,v])=>`<div class="acct17-exp-row"><span>${E(k)}</span><b>${R(v)}</b></div>`).join(''):'<div class="empty">No expenses in this tax year.</div>'}</div>`}
function taxData(){const y=N($('#acct17TaxYear')?.value)||currentTaxYear(),[from,to]=taxBounds(y),db=read();return{y,from,to,db,m:metrics(db,from,to)}}
function printTax(){const {y,from,to,db,m}=taxData(),w=open('','_blank');if(!w)return;const rows=monthKeys(y).map(k=>{const a=k+'-01',d=new Date(Number(k.slice(0,4)),Number(k.slice(5,7)),0),b=D(d),x=metrics(db,a,b);return`<tr><td>${E(monthLabel(k))}</td><td>${R(x.sales)}</td><td>${R(x.vendorPaid)}</td><td>${R(x.expenses)}</td><td>${R(x.net)}</td></tr>`}).join('');w.document.write(`<!doctype html><html><head><title>Tax Year ${y} Business Summary</title><style>@page{size:A4;margin:12mm}body{font-family:Arial;color:#161616}h1{color:#d71920;margin:0}.muted{color:#666;font-size:11px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:14px 0}.box{border:1px solid #ddd;padding:9px;border-radius:7px}.box span{font-size:9px;color:#666}.box b{display:block;font-size:16px;margin-top:4px}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #ddd;padding:7px;font-size:10px;text-align:left}th{background:#17191d;color:white}</style></head><body><h1>Design Line Agency</h1><div class="muted">Tax Year ${y} Business Working • ${from} to ${to}</div><div class="grid"><div class="box"><span>Sales</span><b>${R(m.sales)}</b></div><div class="box"><span>Vendor Payments</span><b>${R(m.vendorPaid)}</b></div><div class="box"><span>Expenses</span><b>${R(m.expenses)}</b></div><div class="box"><span>Net Profit</span><b>${R(m.net)}</b></div><div class="box"><span>Received</span><b>${R(m.received)}</b></div><div class="box"><span>Pending</span><b>${R(m.pending)}</b></div></div><table><thead><tr><th>Month</th><th>Sales</th><th>Vendor Payments</th><th>Expenses</th><th>Net Profit</th></tr></thead><tbody>${rows}</tbody></table><p class="muted">Working formula: Sales − Vendor Payments − Expenses = Net Profit. Verify tax adjustments before filing.</p><script>window.onload=()=>print()<\/script></body></html>`);w.document.close()}
function csvCell(v){return `"${String(v??'').replace(/"/g,'""')}"`}
function exportTax(){const {y,db}=taxData(),rows=[['Month','Sales','Vendor Payments','Expenses','Net Profit','Received','Pending']];monthKeys(y).forEach(k=>{const a=k+'-01',d=new Date(Number(k.slice(0,4)),Number(k.slice(5,7)),0),b=D(d),x=metrics(db,a,b);rows.push([monthLabel(k),x.sales,x.vendorPaid,x.expenses,x.net,x.received,x.pending])});const blob=new Blob([rows.map(r=>r.map(csvCell).join(',')).join('\n')],{type:'text/csv;charset=utf-8'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`DesignLine_TaxYear_${y}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
let timer=null;function schedule(){clearTimeout(timer);timer=setTimeout(()=>renderReports(false),80)}
function init(){injectStyle();document.addEventListener('change',e=>{if(['reportRange','v7From','v7To'].includes(e.target?.id))setTimeout(()=>renderReports(true),30)},true);document.addEventListener('click',e=>{const b=e.target.closest?.('[data-view="reports"],[data-jump="reports"]');if(b)setTimeout(()=>renderReports(true),100)},true);new MutationObserver(ms=>{if(!$('#reportsView')?.classList.contains('active'))return;const box=$('#reportCards'),labels=box?[...box.querySelectorAll('.stat-label')].map(x=>x.textContent.trim()).join('|'):'';const expected='Sales|Received|Customer Pending|Vendor Payments|Expenses|Net Profit';if(labels!==expected)return schedule();if(ms.every(m=>m.target?.closest?.('#reportCards,#acct17TaxPanel,#v7Breakdown')))return;schedule()}).observe(document.body,{childList:true,subtree:true});setTimeout(()=>renderReports(true),150)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();