const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>'Rs '+Number(n||0).toLocaleString('en-PK');
const iso=()=>new Date().toISOString().slice(0,10);
const uid=p=>p+'-'+Date.now().toString().slice(-6)+Math.floor(Math.random()*90+10);
const defaultData={
 settings:{agencyName:'Design Line Agency',phone:'',officeHours:'08:00 AM - 09:00 PM',defaultAdvance:75,apiUrl:''},
 customers:[{id:'C-001',name:'Ali Raza',phone:'03001234567'},{id:'C-002',name:'Hamza Foods',phone:'03111234567'},{id:'C-003',name:'City Clinic',phone:'03221234567'}],
 vendors:[{id:'V-001',name:'Gujranwala Flex Vendor',phone:'03005551111',notes:'Flex printing outsourced'},{id:'V-002',name:'Offset Press Partner',phone:'03115552222',notes:'Boxes & offset jobs'}],
 orders:[
 {id:'ORD-1001',date:iso(),customerId:'C-001',service:'Flex Printing',item:'10x10 ft flex',qty:100,unit:'sq ft',rate:38,designCharges:500,fittingCharges:0,vendorId:'V-001',vendorCost:2700,total:4300,advance:3225,status:'In Progress',due:iso(),notes:'75% advance received'},
 {id:'ORD-1002',date:iso(),customerId:'C-002',service:'Offset / Packaging',item:'Burger Boxes',qty:1000,unit:'pcs',rate:30,designCharges:0,fittingCharges:0,vendorId:'V-002',vendorCost:16500,total:30000,advance:20000,status:'Ready',due:iso(),notes:'Paper/printing based cost'},
 {id:'ORD-1003',date:iso(),customerId:'C-003',service:'Digital Print',item:'A4 Color Prints',qty:40,unit:'prints',rate:70,designCharges:500,fittingCharges:0,vendorId:'',vendorCost:700,total:3300,advance:3300,status:'Delivered',due:iso(),notes:''}
 ],
 quotes:[{id:'Q-501',date:iso(),customerId:'C-002',type:'offset',item:'1 lb Cake Box - 1000 pcs',amount:28000},{id:'Q-502',date:iso(),customerId:'C-001',type:'digital',item:'Passport Photos + A4 Prints',amount:1800}],
 expenses:[{id:'E-101',date:iso(),category:'Electricity',description:'Daily office share',amount:1200,paidBy:'CEO'},{id:'E-102',date:iso(),category:'Delivery',description:'Vendor pickup',amount:450,paidBy:'Staff'}]
};
let db=load();
function load(){try{return JSON.parse(localStorage.getItem('designlineERP'))||structuredClone(defaultData)}catch{return structuredClone(defaultData)}}
function save(){localStorage.setItem('designlineERP',JSON.stringify(db));syncBackend();renderAll()}
function toast(m){$('#toast').textContent=m;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function cust(id){return db.customers.find(x=>x.id===id)||{name:'Unknown',phone:''}}
function vendor(id){return db.vendors.find(x=>x.id===id)||{name:'—'}}
function balance(o){return Math.max(0,(+o.total||0)-(+o.advance||0))}
function profit(o){return (+o.total||0)-(+o.vendorCost||0)}
function expenseTotal(list=db.expenses){return list.reduce((a,x)=>a+(+x.amount||0),0)}
function renderAll(){applyRole();renderDashboard();renderOrders();renderQuotes();renderCustomers();renderExpenses();renderVendors();renderReports();loadSettings()}
function applyRole(){let role=$('#roleSelect').value;$$('.admin-only').forEach(el=>el.classList.toggle('hidden',role==='staff'))}
function renderDashboard(){let sales=db.orders.reduce((a,o)=>a+(+o.total||0),0), costs=db.orders.reduce((a,o)=>a+(+o.vendorCost||0),0), exp=expenseTotal(), prof=sales-costs-exp, pending=db.orders.reduce((a,o)=>a+balance(o),0);$('#dashboardCards').innerHTML=stat('Total Sales',fmt(sales),'All recorded orders')+stat('Net Profit',fmt(prof),'Sales - vendor cost - expenses')+stat('Pending Bills',fmt(pending),db.orders.filter(o=>balance(o)>0).length+' orders')+stat('Expenses',fmt(exp),db.expenses.length+' entries');$('#pendingBadge').textContent=db.orders.filter(o=>balance(o)>0).length+' Pending Bills';$('#recentOrders').innerHTML=db.orders.slice(-5).reverse().map(o=>`<div class="recent-item"><div><b>${o.id}</b><div class="muted">${cust(o.customerId).name} · ${o.service}</div></div><div><b>${fmt(o.total)}</b><div class="muted">${o.status}</div></div></div>`).join('')||'<p class="muted">No orders.</p>';$('#pendingBills').innerHTML=db.orders.filter(o=>balance(o)>0).slice(0,5).map(o=>`<div class="bill-item"><div><b>${cust(o.customerId).name}</b><div class="muted">${o.id} · Due ${o.due||'—'}</div></div><b class="money negative">${fmt(balance(o))}</b></div>`).join('')||'<p class="muted">No pending bills.</p>';let by={};db.orders.forEach(o=>by[o.service]=(by[o.service]||0)+(+o.total||0));let max=Math.max(1,...Object.values(by));$('#serviceBars').innerHTML=Object.entries(by).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="bar-row"><span>${k}</span><div class="bar"><i style="width:${v/max*100}%"></i></div><b>${fmt(v)}</b></div>`).join('')}
function stat(a,b,c){return `<div class="stat"><span>${a}</span><strong>${b}</strong><small>${c}</small></div>`}
function renderOrders(){let q=$('#orderSearch').value.toLowerCase(),st=$('#orderStatusFilter').value;let rows=db.orders.filter(o=>(!st||o.status===st)&&[o.id,cust(o.customerId).name,o.service,o.item].join(' ').toLowerCase().includes(q));$('#ordersBody').innerHTML=rows.map(o=>`<tr><td><b>${o.id}</b><div class="muted">${o.date}</div></td><td>${cust(o.customerId).name}</td><td>${o.service}<div class="muted">${o.item||''}</div></td><td>${fmt(o.total)}</td><td>${fmt(o.advance)}</td><td class="money ${balance(o)?'negative':'positive'}">${fmt(balance(o))}</td><td><span class="status status-${o.status.replaceAll(' ','-')}">${o.status}</span></td><td>${o.due||'—'}</td><td><div class="row-actions"><button class="icon-btn" onclick="editOrder('${o.id}')">Edit</button><button class="icon-btn" onclick="printInvoice('${o.id}')">Invoice</button></div></td></tr>`).join('')}
function renderQuotes(){let type=$('#quoteTypeFilter').value;$('#quotesBody').innerHTML=db.quotes.filter(q=>!type||q.type===type).map(q=>`<tr><td><b>${q.id}</b></td><td>${cust(q.customerId).name}</td><td>${q.type==='offset'?'Offset / Packaging':'Digital Print'}</td><td>${q.item}</td><td>${fmt(q.amount)}</td><td>${q.date}</td><td><button class="icon-btn" onclick="printQuote('${q.id}')">Print</button></td></tr>`).join('')}
function renderCustomers(){let q=$('#customerSearch').value.toLowerCase();$('#customersBody').innerHTML=db.customers.filter(c=>(c.name+' '+c.phone).toLowerCase().includes(q)).map(c=>{let os=db.orders.filter(o=>o.customerId===c.id),s=os.reduce((a,o)=>a+(+o.total||0),0),p=os.reduce((a,o)=>a+balance(o),0);return `<tr><td><b>${c.name}</b></td><td>${c.phone||'—'}</td><td>${os.length}</td><td>${fmt(s)}</td><td class="money ${p?'negative':''}">${fmt(p)}</td><td>${c.phone?`<button class="icon-btn" onclick="whatsapp('${c.phone}','${c.name}')">Message</button>`:'—'}</td></tr>`}).join('')}
function renderExpenses(){let total=expenseTotal(),today=db.expenses.filter(e=>e.date===iso()).reduce((a,e)=>a+(+e.amount||0),0);$('#expenseCards').innerHTML=stat('Total Expenses',fmt(total),'All time')+stat('Today',fmt(today),'Today\'s expense')+stat('Entries',db.expenses.length,'Recorded transactions');$('#expensesBody').innerHTML=db.expenses.slice().reverse().map(e=>`<tr><td>${e.date}</td><td>${e.category}</td><td>${e.description}</td><td>${fmt(e.amount)}</td><td>${e.paidBy}</td><td class="admin-only"><button class="icon-btn" onclick="deleteExpense('${e.id}')">Delete</button></td></tr>`).join('');applyRole()}
function renderVendors(){ $('#vendorsBody').innerHTML=db.vendors.map(v=>{let os=db.orders.filter(o=>o.vendorId===v.id),cost=os.reduce((a,o)=>a+(+o.vendorCost||0),0);return `<tr><td><b>${v.name}</b></td><td>${v.phone||'—'}</td><td>${os.length}</td><td>${fmt(cost)}</td><td>${fmt(0)}</td><td>${v.notes||'—'}</td></tr>`}).join('')}
function dateFilter(d,range){let x=new Date(d+'T00:00:00'),now=new Date();if(range==='all')return true;if(range==='today')return d===iso();if(range==='month')return x.getMonth()===now.getMonth()&&x.getFullYear()===now.getFullYear();let day=(now.getDay()+6)%7,start=new Date(now);start.setDate(now.getDate()-day);start.setHours(0,0,0,0);return x>=start&&x<=now}
function renderReports(){let r=$('#reportRange').value,os=db.orders.filter(o=>dateFilter(o.date,r)),es=db.expenses.filter(e=>dateFilter(e.date,r));let sales=os.reduce((a,o)=>a+(+o.total||0),0),vc=os.reduce((a,o)=>a+(+o.vendorCost||0),0),ex=expenseTotal(es),pr=sales-vc-ex,rec=os.reduce((a,o)=>a+balance(o),0);$('#reportCards').innerHTML=stat('Sales',fmt(sales),os.length+' orders')+stat('Vendor Cost',fmt(vc),'Outsourced jobs')+stat('Expenses',fmt(ex),es.length+' entries')+stat('Net Profit',fmt(pr),'Margin '+(sales?Math.round(pr/sales*100):0)+'%');let by={};os.forEach(o=>{by[o.service]=(by[o.service]||0)+profit(o)});$('#profitService').innerHTML=Object.entries(by).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="bill-item"><span>${k}</span><b>${fmt(v)}</b></div>`).join('')||'<p class="muted">No data.</p>';$('#receivables').innerHTML=os.filter(o=>balance(o)>0).map(o=>`<div class="bill-item"><span>${cust(o.customerId).name}<div class="muted">${o.id}</div></span><b class="money negative">${fmt(balance(o))}</b></div>`).join('')||'<p class="muted">No receivables.</p>'}
function openForm(title,fields,onSubmit,values={}){$('#modalTitle').textContent=title;let f=$('#dynamicForm');f.innerHTML=`<div class="form-grid">${fields.map(x=>fieldHtml(x,values[x.name])).join('')}<div class="form-actions"><button type="button" class="ghost" onclick="closeModal()">Cancel</button><button class="primary">Save</button></div></div>`;f.onsubmit=e=>{e.preventDefault();let fd=Object.fromEntries(new FormData(f).entries());onSubmit(fd);closeModal()};$('#modal').classList.add('open')}
function fieldHtml(x,val){let cls=x.full?'field full-span':'field',v=val??x.value??'';if(x.type==='select')return `<label class="${cls}"><span>${x.label}</span><select name="${x.name}" ${x.required?'required':''}>${x.options.map(o=>{let a=Array.isArray(o)?o:[o,o];return `<option value="${a[0]}" ${String(v)===String(a[0])?'selected':''}>${a[1]}</option>`}).join('')}</select></label>`;if(x.type==='textarea')return `<label class="${cls}"><span>${x.label}</span><textarea name="${x.name}">${v}</textarea></label>`;return `<label class="${cls}"><span>${x.label}</span><input name="${x.name}" type="${x.type||'text'}" value="${v}" ${x.required?'required':''} ${x.step?`step="${x.step}"`:''}></label>`}
window.closeModal=()=>$('#modal').classList.remove('open');
const services=['Flex Printing','Wallpaper + Fitting','Digital Print','Photocopy Black','Sublimation','Offset / Packaging','Passport Photos','Wedding Cards','Graphic Design','Other'];
function orderFields(){return [{name:'date',label:'Order Date',type:'date',value:iso(),required:true},{name:'customerId',label:'Customer',type:'select',options:db.customers.map(c=>[c.id,c.name]),required:true},{name:'service',label:'Service',type:'select',options:services,required:true},{name:'item',label:'Item / Job Detail',required:true},{name:'qty',label:'Quantity / Sq Ft',type:'number',step:'0.01',value:1},{name:'unit',label:'Unit',value:'pcs'},{name:'rate',label:'Rate',type:'number',step:'0.01',value:0},{name:'designCharges',label:'Design Charges',type:'number',step:'0.01',value:0},{name:'fittingCharges',label:'Fitting Charges',type:'number',step:'0.01',value:0},{name:'vendorId',label:'Vendor',type:'select',options:[['','No Vendor'],...db.vendors.map(v=>[v.id,v.name])]},{name:'vendorCost',label:'Vendor / Production Cost',type:'number',step:'0.01',value:0},{name:'advance',label:'Advance Received',type:'number',step:'0.01',value:0},{name:'status',label:'Status',type:'select',options:['New','In Progress','Ready','Delivered']},{name:'due',label:'Due / Delivery Date',type:'date',value:iso()},{name:'notes',label:'Notes',type:'textarea',full:true}]}
function addOrder(){openForm('New Order',orderFields(),d=>{d.id=uid('ORD');['qty','rate','designCharges','fittingCharges','vendorCost','advance'].forEach(k=>d[k]=+d[k]||0);d.total=d.qty*d.rate+d.designCharges+d.fittingCharges;db.orders.push(d);save();toast('Order added')})}
window.editOrder=id=>{let o=db.orders.find(x=>x.id===id);openForm('Edit '+id,orderFields(),d=>{['qty','rate','designCharges','fittingCharges','vendorCost','advance'].forEach(k=>d[k]=+d[k]||0);Object.assign(o,d,{total:d.qty*d.rate+d.designCharges+d.fittingCharges});save();toast('Order updated')},o)}
function addQuote(){let fields=[{name:'date',label:'Date',type:'date',value:iso()},{name:'customerId',label:'Customer',type:'select',options:db.customers.map(c=>[c.id,c.name])},{name:'type',label:'Quotation Type',type:'select',options:[['offset','Offset / Packaging'],['digital','Digital Print']]},{name:'item',label:'Item / Details',full:true},{name:'amount',label:'Quoted Amount',type:'number',step:'0.01'}];openForm('New Quotation',fields,d=>{d.id=uid('Q');d.amount=+d.amount||0;db.quotes.push(d);save();toast('Quotation saved')})}
function addCustomer(){openForm('Add Customer',[{name:'name',label:'Customer Name',required:true},{name:'phone',label:'Phone / WhatsApp'}],d=>{d.id=uid('C');db.customers.push(d);save();toast('Customer added')})}
function addExpense(){openForm('Add Expense',[{name:'date',label:'Date',type:'date',value:iso()},{name:'category',label:'Category',type:'select',options:['Electricity','Rent','Salary','Delivery','Internet','Stationery','Maintenance','Tea / Food','Other']},{name:'description',label:'Description',full:true},{name:'amount',label:'Amount',type:'number',step:'0.01',required:true},{name:'paidBy',label:'Paid By',type:'select',options:['CEO','Staff']}],d=>{d.id=uid('E');d.amount=+d.amount||0;db.expenses.push(d);save();toast('Expense added')})}
window.deleteExpense=id=>{if(confirm('Delete this expense?')){db.expenses=db.expenses.filter(x=>x.id!==id);save();toast('Expense deleted')}}
function addVendor(){openForm('Add Vendor',[{name:'name',label:'Vendor Name',required:true},{name:'phone',label:'Phone'},{name:'notes',label:'Notes',type:'textarea',full:true}],d=>{d.id=uid('V');db.vendors.push(d);save();toast('Vendor added')})}
window.whatsapp=(phone,name)=>{let clean=phone.replace(/\D/g,'').replace(/^0/,'92');window.open(`https://wa.me/${clean}?text=${encodeURIComponent('Assalam-o-Alaikum '+name+', Design Line Agency se aap ke order/bill ke hawale se rabta kar rahe hain.')}`,'_blank')}
window.printInvoice=id=>{let o=db.orders.find(x=>x.id===id),c=cust(o.customerId);printDoc('INVOICE',`<h2>${db.settings.agencyName}</h2><p>Order: ${o.id} | Date: ${o.date}</p><hr><p><b>Customer:</b> ${c.name} ${c.phone?'· '+c.phone:''}</p><p><b>Service:</b> ${o.service}</p><p><b>Job:</b> ${o.item}</p><table><tr><td>Qty</td><td>${o.qty} ${o.unit}</td></tr><tr><td>Rate</td><td>${fmt(o.rate)}</td></tr><tr><td>Design Charges</td><td>${fmt(o.designCharges)}</td></tr><tr><td>Fitting Charges</td><td>${fmt(o.fittingCharges)}</td></tr><tr><th>Total</th><th>${fmt(o.total)}</th></tr><tr><td>Advance</td><td>${fmt(o.advance)}</td></tr><tr><th>Balance</th><th>${fmt(balance(o))}</th></tr></table>`)}
window.printQuote=id=>{let q=db.quotes.find(x=>x.id===id),c=cust(q.customerId);printDoc('QUOTATION',`<h2>${db.settings.agencyName}</h2><p>${q.id} · ${q.date}</p><hr><p><b>Customer:</b> ${c.name}</p><p><b>Type:</b> ${q.type==='offset'?'Offset / Packaging':'Digital Print'}</p><p><b>Details:</b> ${q.item}</p><h2>Total: ${fmt(q.amount)}</h2>`)}
function printDoc(title,body){let w=window.open('','_blank');w.document.write(`<title>${title}</title><style>body{font-family:Arial;padding:35px;color:#111}table{width:100%;border-collapse:collapse;margin-top:20px}td,th{border:1px solid #ddd;padding:10px;text-align:left}h2{color:#d71920}</style>${body}<script>print()<\/script>`);w.document.close()}
function exportCsv(){let rows=[['Order ID','Date','Customer','Service','Item','Total','Advance','Balance','Vendor Cost','Profit','Status'],...db.orders.map(o=>[o.id,o.date,cust(o.customerId).name,o.service,o.item,o.total,o.advance,balance(o),o.vendorCost,profit(o),o.status])];let csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='design-line-orders.csv';a.click()}
function loadSettings(){let s=db.settings||{};$('#agencyName').value=s.agencyName||'Design Line Agency';$('#agencyPhone').value=s.phone||'';$('#officeHours').value=s.officeHours||'';$('#defaultAdvance').value=s.defaultAdvance||75;$('#apiUrl').value=s.apiUrl||'';$('#backendStatus').textContent=s.apiUrl?'Backend URL saved. Data sync will be attempted on every save.':'Currently running in Local Demo mode (browser storage).'}
async function syncBackend(){let url=db.settings?.apiUrl;if(!url)return;try{await fetch(url,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify({action:'syncAll',data:db})})}catch(e){console.warn('Backend sync failed',e)}}
$$('.nav-btn').forEach(b=>b.onclick=()=>{if(b.classList.contains('hidden'))return;$$('.nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active'));$('#'+b.dataset.view+'View').classList.add('active');$('#pageTitle').textContent=b.textContent;$('#sidebar').classList.remove('open')});
$$('[data-jump]').forEach(b=>b.onclick=()=>document.querySelector(`.nav-btn[data-view="${b.dataset.jump}"]`).click());
$('#roleSelect').onchange=renderAll;$('#themeToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('dlTheme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('dlTheme')==='dark')document.body.classList.add('dark');
$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
$('#quickOrderBtn').onclick=$('#newOrderBtn').onclick=addOrder;$('#newQuoteBtn').onclick=addQuote;$('#newCustomerBtn').onclick=addCustomer;$('#newExpenseBtn').onclick=addExpense;$('#newVendorBtn').onclick=addVendor;$('#orderSearch').oninput=renderOrders;$('#orderStatusFilter').onchange=renderOrders;$('#quoteTypeFilter').onchange=renderQuotes;$('#customerSearch').oninput=renderCustomers;$('#reportRange').onchange=renderReports;$('#exportCsvBtn').onclick=exportCsv;
$('#saveSettingsBtn').onclick=()=>{db.settings={...db.settings,agencyName:$('#agencyName').value,phone:$('#agencyPhone').value,officeHours:$('#officeHours').value,defaultAdvance:+$('#defaultAdvance').value||75};save();toast('Settings saved')};$('#saveApiBtn').onclick=()=>{db.settings.apiUrl=$('#apiUrl').value.trim();save();toast('Backend URL saved')};$('#resetDemoBtn').onclick=()=>{if(confirm('Reset all ERP data to demo data?')){db=structuredClone(defaultData);save();toast('Demo data reset')}};
$('#todayText').textContent=new Date().toLocaleDateString('en-PK',{weekday:'long',year:'numeric',month:'long',day:'numeric'})+' · Office 8:00 AM – 9:00 PM';renderAll();
