(()=>{'use strict';
const K='designlineERP_v2',U='designlineERP_cloud_url',BOOT='designlineERP_cloud_boot';
const rawSet=Storage.prototype.setItem;
let internal=false,pushTimer=null,lastPushed='';
const SHEET_URL='https://docs.google.com/spreadsheets/d/1zm0XvdY6zYREUIvVbHf7pRoZCnWHgandxjgObYNi4uk/edit';
const DEFAULT_API_URL='https://script.google.com/macros/s/AKfycbz5XfyYCP5-fmsTP5FOHeu8_4AbNNFzwxM2Z_h-g-jxXHMtlNW_4QEJeOHOdr33Fkk6ag/exec';
const norm=u=>String(u||'').trim().replace(/\/$/,'');
function localDb(){try{return JSON.parse(localStorage.getItem(K)||'null')}catch(e){return null}}
function endpoint(d){return norm(d?.settings?.apiUrl||localStorage.getItem(U)||DEFAULT_API_URL)}
function pill(t,bad=false){const e=document.getElementById('storagePill');if(e){e.textContent=t;e.style.color=bad?'#ff6b6b':''}}
function status(t,bad=false){const e=document.getElementById('backendStatus');if(e){e.textContent=t;e.style.color=bad?'#ff6b6b':''}}
async function postCloud(u,data){if(!u||!data)return;try{await fetch(u,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'syncAll',data})});pill('● Cloud Sync');status('Cloud save sent to Google Sheets.')}catch(e){pill('● Cloud Offline',true);status('Cloud save failed — local copy is safe.',true)}}
function schedulePush(serialized){clearTimeout(pushTimer);pushTimer=setTimeout(()=>{try{const d=JSON.parse(serialized);const u=endpoint(d);if(!u)return;if(serialized===lastPushed)return;lastPushed=serialized;postCloud(u,d)}catch(e){}},500)}
Storage.prototype.setItem=function(key,value){if(this===localStorage&&key===K&&!internal){try{const d=JSON.parse(value);d.settings=d.settings||{};const u=endpoint(d);if(u){d.settings.apiUrl=u;rawSet.call(localStorage,U,u)}d.settings.clientUpdatedAt=Date.now();d.settings.storageMode='Google Sheets Cloud';value=JSON.stringify(d)}catch(e){}rawSet.call(this,key,value);schedulePush(value);return}return rawSet.call(this,key,value)};
function jsonp(u,action='load',timeout=15000){return new Promise((resolve,reject)=>{const cb='__dlCloudCb_'+Date.now()+'_'+Math.floor(Math.random()*100000);const s=document.createElement('script');let done=false;const finish=(err,val)=>{if(done)return;done=true;clearTimeout(tm);try{delete window[cb]}catch(e){};s.remove();err?reject(err):resolve(val)};window[cb]=v=>finish(null,v);s.onerror=()=>finish(new Error('Cloud request failed'));s.src=u+(u.includes('?')?'&':'?')+'action='+encodeURIComponent(action)+'&callback='+encodeURIComponent(cb)+'&_='+Date.now();document.head.appendChild(s);const tm=setTimeout(()=>finish(new Error('Cloud request timeout')),timeout)})}
async function pullCloud(force=false){const local=localDb(),u=endpoint(local);if(!u){status('Cloud endpoint missing.',true);return {ok:false}}rawSet.call(localStorage,U,u);pill('● Checking Cloud');try{const r=await jsonp(u,'load');if(!r||!r.ok)throw new Error(r?.error||'Cloud response invalid');if(!r.data){pill('● Cloud Ready');status('Cloud database is ready. Current browser data will become the first cloud copy after the next save.');return r}const remote=r.data;remote.settings=remote.settings||{};remote.settings.apiUrl=u;const rt=Number(remote.settings.clientUpdatedAt||r.updatedAtMs||0),lt=Number(local?.settings?.clientUpdatedAt||0);if(force||!local||rt>lt){internal=true;rawSet.call(localStorage,K,JSON.stringify(remote));rawSet.call(localStorage,U,u);internal=false;pill('● Cloud Loaded');status('Latest Google Sheets database loaded.');const mark=String(r.updatedAtMs||rt||Date.now());if(sessionStorage.getItem(BOOT)!==mark){sessionStorage.setItem(BOOT,mark);setTimeout(()=>location.reload(),150)}}else if(local&&lt>rt){postCloud(u,local);pill('● Cloud Sync');status('Local changes are newer and were sent to cloud.')}else{pill('● Cloud Sync');status('Cloud database is connected and up to date.')}return r}catch(e){pill('● Local Save',true);status('Cloud unavailable right now. ERP is using its safe local copy.',true);return {ok:false,error:String(e)}}}
async function testCloud(){const u=norm(document.getElementById('apiUrl')?.value||endpoint(localDb()));if(!u){status('Apps Script URL required.',true);return}pill('● Testing Cloud');try{const r=await jsonp(u,'ping',10000);if(r?.ok){rawSet.call(localStorage,U,u);pill('● Cloud Connected');status('Google Sheets cloud connection successful.')}else throw new Error('No response')}catch(e){pill('● Cloud Error',true);status('Cloud test failed. Check Apps Script deployment URL.',true)}}
function mountUi(){const api=document.getElementById('apiUrl');if(!api)return;const wrap=api.parentElement;wrap.style.display='block';wrap.className='panel';wrap.innerHTML=`<span class="section-kicker">CLOUD DATABASE</span><h3>Google Sheets Cloud Sync</h3><p class="muted">GitHub Pages runs the ERP. Google Sheets stores the shared live database for PC and mobile.</p><label class="field"><span>Apps Script Web App URL</span><input id="apiUrl" placeholder="https://script.google.com/macros/s/.../exec"></label><div class="form-actions left" style="margin-top:12px"><button class="primary" id="saveApiBtn" type="button">Save Cloud URL</button><button class="ghost" id="testApiBtn" type="button">Test Cloud</button><button class="ghost" id="pullCloudBtn" type="button">Pull Latest</button><button class="ghost" id="pushCloudBtn" type="button">Push Now</button></div><div class="backend-box" id="backendStatus">Permanent cloud endpoint configured.</div><p class="muted" style="margin-top:10px"><a href="${SHEET_URL}" target="_blank" rel="noopener">Open DesignLine ERP Cloud Database Sheet</a></p>`;
const saved=endpoint(localDb());rawSet.call(localStorage,U,saved);document.getElementById('apiUrl').value=saved;
document.getElementById('saveApiBtn').addEventListener('click',()=>{const u=norm(document.getElementById('apiUrl').value||DEFAULT_API_URL);if(u)rawSet.call(localStorage,U,u)},true);
document.getElementById('testApiBtn').addEventListener('click',e=>{e.stopImmediatePropagation();testCloud()},true);
document.getElementById('pullCloudBtn').onclick=()=>pullCloud(true);
document.getElementById('pushCloudBtn').onclick=()=>{const d=localDb(),u=endpoint(d);u&&d?postCloud(u,d):status('Cloud database not ready.',true)};
const sys=document.getElementById('firebaseBackendStatus');if(sys)sys.textContent='Google Sheets cloud database is connected. Firebase is not used.'}
window.DesignLineCloud={pull:pullCloud,push:()=>{const d=localDb(),u=endpoint(d);return postCloud(u,d)},test:testCloud,sheetUrl:SHEET_URL,apiUrl:DEFAULT_API_URL};
rawSet.call(localStorage,U,DEFAULT_API_URL);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mountUi,{once:true});else mountUi();
setTimeout(()=>pullCloud(false),50);
})();