(()=>{'use strict';
const K='designlineERP_v2',$=s=>document.querySelector(s),N=x=>Number(x)||0,R=x=>'Rs '+N(x).toLocaleString('en-PK'),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=()=>{try{return JSON.parse(localStorage.getItem(K))||{}}catch{return{}}};
function lines(o){return Array.isArray(o?.lineItems)&&o.lineItems.length?o.lineItems:[o||{}]}
function flex(x){return ['Flex Printing','Wallpaper + Fitting'].includes(x?.service)}
function area(x){return N(x.widthFt)&&N(x.heightFt)?N(x.widthFt)*N(x.heightFt)*Math.max(1,N(x.panels)||1):N(x.qty)}
function lineSale(x){const s=x?.service||'Other';if(flex(x))return area(x)*N(x.rate)+N(x.designCharges)+N(x.fittingCharges)+N(x.otherCharges);if(s==='Passport Photos')return N(x.qty)*N(x.rate)+N(x.retouchCharges)+N(x.otherCharges);if(s==='ID / Document Print')return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.laminationCharges)+N(x.otherCharges);return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.finishingCharges)+N(x.fittingCharges)+N(x.otherCharges)}
const orderSale=o=>lines(o).reduce((a,l)=>a+lineSale(l),0);
const orderReceived=(db,o)=>N(o.advance)+(db.payments||[]).filter(p=>p.orderId===o.id).reduce((a,p)=>a+N(p.amount),0);
function card(label,value,foot,accent){return `<div class="stat-card" style="--accent:${accent}"><div class="stat-top"><span class="stat-label">${E(label)}</span></div><strong class="stat-value">${R(value)}</strong><div class="stat-foot">${E(foot)}</div></div>`}
function render(){const box=$('#dashboardCards');if(!box)return;const db=read(),orders=(db.orders||[]).filter(o=>o.status!=='Cancelled'),sales=orders.reduce((a,o)=>a+orderSale(o),0),received=orders.reduce((a,o)=>a+orderReceived(db,o),0),pending=orders.reduce((a,o)=>a+Math.max(0,orderSale(o)-orderReceived(db,o)),0),vendorPayments=(db.vendorPayments||[]),vendorPaid=vendorPayments.reduce((a,p)=>a+N(p.amount),0),expenses=(db.expenses||[]).reduce((a,e)=>a+N(e.amount),0),net=sales-vendorPaid-expenses,expected=['Total Sales','Received','Pending Bills','Vendor Payments','Expenses','Net Profit'],labels=[...box.querySelectorAll('.stat-label')].map(x=>x.textContent.trim());const sig=JSON.stringify([sales,received,pending,vendorPaid,vendorPayments.length,expenses,net,orders.length]);if(box.dataset.v19sig===sig&&labels.join('|')===expected.join('|'))return;box.dataset.v19sig=sig;box.className='cards dashboard-v19';box.innerHTML=card('Total Sales',sales,`${orders.length} active orders`,'#3077d5')+card('Received',received,'Customer collections received','#14945c')+card('Pending Bills',pending,`${orders.filter(o=>Math.max(0,orderSale(o)-orderReceived(db,o))>0).length} customer bills pending`,'#e31b23')+card('Vendor Payments',vendorPaid,`${vendorPayments.length} payment entr${vendorPayments.length===1?'y':'ies'} • Vendor Ledger paid`,'#d98324')+card('Expenses',expenses,'Office / material / other expenses','#b95d2a')+card('Net Profit',net,'Sales − Vendor Payments − Expenses','#14945c');const brand=$('.brand span');if(brand)brand.textContent='Agency ERP • Cloud • V22'}
function style(){if($('#dashV19Style'))return;const s=document.createElement('style');s.id='dashV19Style';s.textContent='#dashboardCards.dashboard-v19{grid-template-columns:repeat(3,minmax(0,1fr))!important}@media(max-width:1000px){#dashboardCards.dashboard-v19{grid-template-columns:repeat(2,minmax(0,1fr))!important}}@media(max-width:600px){#dashboardCards.dashboard-v19{grid-template-columns:1fr!important}}';document.head.appendChild(s)}
let t;function schedule(){clearTimeout(t);t=setTimeout(render,25)}
function init(){style();render();new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});window.addEventListener('storage',e=>{if(e.key===K)render()});window.addEventListener('designline:cloudloaded',render);setInterval(render,1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();