(()=>{'use strict';
const STORE='designlineERP_custom_dropdowns_v1';
const MAIN='designlineERP_v2';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=()=>{try{return JSON.parse(localStorage.getItem(STORE))||{}}catch(e){return{}}};
const write=x=>{localStorage.setItem(STORE,JSON.stringify(x));renderManager();refreshFilters()};
const readMain=()=>{try{return JSON.parse(localStorage.getItem(MAIN))||{}}catch(e){return{}}};
const EXCLUDE=new Set(['customerId','vendorId']);
function keyFor(sel){const n=sel.name||sel.id||'select';if(n==='service'||sel.id==='orderServiceFilter'||sel.id==='quoteTypeFilter')return'service';if(n==='category'||sel.id==='expenseCategoryFilter')return'expenseCategory';if(n==='status'||sel.id==='orderStatusFilter')return'status';if(n==='method')return'paymentMethod';if(n==='paidBy')return'paidBy';const f=sel.closest('#dynamicForm'),svc=f&&f.elements&&f.elements.service?f.elements.service.value:'General';return`${svc||'General'}::${n}`}
function valuesFor(key){const x=read()[key];return Array.isArray(x)?x:[]}
function addOptions(sel,key){const current=sel.value;for(const v of valuesFor(key)){if(![...sel.options].some(o=>o.value===v)){const o=document.createElement('option');o.value=v;o.textContent=v;sel.appendChild(o)}}if(current&&[...sel.options].some(o=>o.value===current))sel.value=current}
function desiredValue(sel){const title=($('#modalTitle')||{}).textContent||'';if(!title.startsWith('Edit '))return'';const id=title.replace(/^Edit\s+/,'').trim(),db=readMain();const list=id.startsWith('Q-')?(db.quotes||[]):(db.orders||[]),obj=list.find(x=>x.id===id);return obj&&sel.name?obj[sel.name]||'':''}
function enhance(sel){if(!sel||sel.dataset.ddmReady==='1')return;const key=keyFor(sel);addOptions(sel,key);const desired=desiredValue(sel);if(desired){if(![...sel.options].some(o=>o.value===String(desired))){const o=document.createElement('option');o.value=desired;o.textContent=desired;sel.appendChild(o)}sel.value=String(desired)}const n=sel.name||'';if(!sel.closest('#dynamicForm')||EXCLUDE.has(n)){sel.dataset.ddmReady='1';return}const label=sel.closest('label.field');if(!label){sel.dataset.ddmReady='1';return}const row=document.createElement('div');row.className='ddm-select-row';sel.parentNode.insertBefore(row,sel);row.appendChild(sel);const b=document.createElement('button');b.type='button';b.className='ddm-add';b.title='Add new item';b.textContent='+';b.onclick=e=>{e.preventDefault();e.stopPropagation();addItem(sel)};row.appendChild(b);sel.dataset.ddmReady='1'}
function labelText(sel){const l=sel.closest('label.field'),sp=l&&l.querySelector('span');return sp?sp.textContent.trim():(sel.name||'dropdown')}
function addItem(sel){const key=keyFor(sel),label=labelText(sel),v=(prompt(`${label}\nNayi item / option ka naam likhein:`)||'').trim();if(!v)return;const data=read(),a=Array.isArray(data[key])?data[key]:[];if(!a.some(x=>x.toLowerCase()===v.toLowerCase()))a.push(v);data[key]=a;write(data);addOptions(sel,key);sel.value=v;sel.dispatchEvent(new Event('input',{bubbles:true}));sel.dispatchEvent(new Event('change',{bubbles:true}));setTimeout(refresh,0);toast(`Added: ${v}`)}
function refreshFilters(){const map=[['#orderServiceFilter','service'],['#quoteTypeFilter','service'],['#expenseCategoryFilter','expenseCategory'],['#orderStatusFilter','status']];for(const [q,k] of map){const s=$(q);if(s)addOptions(s,k)}}
function refresh(){for(const s of $$('#dynamicForm select'))enhance(s);refreshFilters();injectManager()}
function prettyKey(k){if(k==='service')return'Service / Material Category';if(k==='expenseCategory')return'Expense Category';if(k==='status')return'Job Status';if(k==='paymentMethod')return'Payment Method';if(k==='paidBy')return'Paid By';const p=k.split('::');return p.length>1?`${p[0]} — ${p[1]}`:k}
function injectManager(){const v=$('#settingsView');if(!v||$('#dropdownManagerPanel'))return;const p=document.createElement('div');p.id='dropdownManagerPanel';p.className='panel';p.innerHTML='<span class="section-kicker">CUSTOM OPTIONS</span><h3>Dropdown Manager</h3><p class="muted">Form ke editable dropdowns ke saath <b>+</b> button diya gaya hai. Yahan aap apni add ki hui items dekh ya remove kar sakte hain.</p><div id="dropdownManagerList"></div><div class="form-actions left" style="margin-top:12px"><button type="button" class="ghost" id="ddmClearAll">Clear All Custom Items</button></div>';v.insertBefore(p,v.lastElementChild);$('#ddmClearAll').onclick=()=>{if(confirm('Remove all custom dropdown items? Historical orders will not be deleted.')){localStorage.removeItem(STORE);refresh();renderManager();toast('Custom dropdown items cleared')}};renderManager()}
function renderManager(){const box=$('#dropdownManagerList');if(!box)return;const data=read(),entries=Object.entries(data).filter(([,a])=>Array.isArray(a)&&a.length);if(!entries.length){box.innerHTML='<div class="empty">No custom dropdown items yet. Use the + button beside a dropdown.</div>';return}box.innerHTML=entries.map(([k,a])=>`<div class="ddm-group"><div class="ddm-group-title">${esc(prettyKey(k))}</div><div class="ddm-tags">${a.map(v=>`<span class="ddm-tag">${esc(v)}<button type="button" data-ddm-remove="1" data-key="${encodeURIComponent(k)}" data-value="${encodeURIComponent(v)}">×</button></span>`).join('')}</div></div>`).join('')}
function removeItem(k,v){const data=read(),a=Array.isArray(data[k])?data[k]:[];data[k]=a.filter(x=>x!==v);if(!data[k].length)delete data[k];write(data);toast(`Removed: ${v}`)}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function styles(){if($('#ddmStyles'))return;const s=document.createElement('style');s.id='ddmStyles';s.textContent='.ddm-select-row{display:flex;align-items:center;gap:7px;width:100%}.ddm-select-row select{flex:1;min-width:0}.ddm-add{width:38px;height:38px;flex:0 0 38px;border:1px solid var(--line);background:var(--surface-2);color:var(--red);border-radius:10px;font-size:22px;line-height:1;font-weight:800}.ddm-add:hover{background:var(--red);color:#fff;border-color:var(--red)}.ddm-group{padding:11px 0;border-bottom:1px solid var(--line)}.ddm-group:last-child{border-bottom:0}.ddm-group-title{font-size:11px;font-weight:800;color:var(--muted);margin-bottom:8px}.ddm-tags{display:flex;flex-wrap:wrap;gap:7px}.ddm-tag{display:inline-flex;align-items:center;gap:7px;padding:6px 7px 6px 10px;border:1px solid var(--line);background:var(--surface-2);border-radius:999px;font-size:11px}.ddm-tag button{border:0;background:transparent;color:var(--red);font-size:16px;line-height:1;padding:0 2px;cursor:pointer}';document.head.appendChild(s)}
function click(e){const b=e.target.closest&&e.target.closest('[data-ddm-remove]');if(!b)return;removeItem(decodeURIComponent(b.dataset.key),decodeURIComponent(b.dataset.value))}
function init(){styles();refresh();document.addEventListener('click',click);const obs=new MutationObserver(()=>refresh());obs.observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();