(()=>{'use strict';
const K='designlineERP_v2',CFG={apiKey:'AIzaSyC8Hx-5PQHT3lNeRvMfSOIZnvm2IkEOBk8',authDomain:'designline-erp.firebaseapp.com',projectId:'designline-erp',storageBucket:'designline-erp.firebasestorage.app',messagingSenderId:'605680724271',appId:'1:605680724271:web:cb3184217ea69e1d8619da'},MAP={customers:'customers',vendors:'vendors',orders:'orders',quotes:'quotations',payments:'payments',expenses:'expenses',vendorPayments:'vendorPayments'},FIN=['vendorCost','vendorBillRef','printingCost','plateQty','plateRate','dieCost','laminationCost','uvFoilCost','cuttingCost','bindingCost','packingCost','transportCost','desiredProfit'];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),N=x=>Number(x)||0,safe=x=>JSON.parse(JSON.stringify(x??{}));
let auth,fs,user,prof,ready=false,busy=false,timer,remoteTimer,unsubs=[],last='';
const nativeSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){nativeSet.call(this,k,v);if(k===K&&ready)queueSync()};
const read=()=>{try{return JSON.parse(localStorage.getItem(K))||{}}catch{return{}}},write=d=>nativeSet.call(localStorage,K,JSON.stringify(d)),boss=()=>prof?.role==='boss',can=p=>boss()||prof?.[p]===true;
const readKey=k=>k==='vendorPayments'?(can('canPayVendors')||can('canViewReports')):k==='expenses'?can('canViewReports'):true,writeKey=k=>k==='vendorPayments'?can('canPayVendors'):true,delKey=k=>k==='vendorPayments'?boss():can('canDelete');
function status(t,bad=false){const x=$('#storagePill');if(x){x.textContent=t;x.style.color=bad?'#ff6268':'#39d98a'}}
function toast(t,bad=false){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');if(bad)x.style.background='#8b1b1f';setTimeout(()=>{x.classList.remove('show');x.style.background=''},2200)}
function calcQ(x){const f=['Flex Printing','Wallpaper + Fitting'].includes(x?.service),a=N(x.widthFt)&&N(x.heightFt)?N(x.widthFt)*N(x.heightFt)*Math.max(1,N(x.panels)||1):N(x.qty);if(f)return a*N(x.rate)+N(x.designCharges)+N(x.fittingCharges)+N(x.otherCharges);if(x.service==='Passport Photos')return N(x.qty)*N(x.rate)+N(x.retouchCharges)+N(x.otherCharges);if(x.service==='ID / Document Print')return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.laminationCharges)+N(x.otherCharges);if(x.service==='Offset / Packaging'&&x.pricingMethod==='cost'){const c=N(x.printingCost)+N(x.plateQty)*N(x.plateRate)+N(x.dieCost)+N(x.laminationCost)+N(x.uvFoilCost)+N(x.cuttingCost)+N(x.bindingCost)+N(x.packingCost)+N(x.transportCost)+N(x.vendorCost);return c+N(x.designCharges)+N(x.otherCharges)+N(x.desiredProfit)}return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.finishingCharges)+N(x.fittingCharges)+N(x.otherCharges)}
function split(r,kind){const pub=safe(r),fin={type:'finance',kind,recordId:String(r.id),lines:{}};const ls=(pub.lineItems||[]).length?pub.lineItems:[pub];ls.forEach((l,i)=>{const id=String(l.id||i),f={};FIN.forEach(k=>{if(l[k]!==undefined)f[k]=l[k]});if(kind==='quote'&&l.pricingMethod!==undefined)f.pricingMethod=l.pricingMethod;if(Object.keys(f).length)fin.lines[id]=f;if(kind==='quote'&&l.service==='Offset / Packaging'&&l.pricingMethod==='cost'){const total=calcQ(l),extras=N(l.designCharges)+N(l.otherCharges),q=Math.max(1,N(l.qty));l.pricingMethod='rate';l.rate=Math.max(0,total-extras)/q}FIN.forEach(k=>delete l[k])});return{pub,fin}}
function merge(r,f){if(!f?.lines)return r;const x=safe(r),ls=(x.lineItems||[]).length?x.lineItems:[x];ls.forEach((l,i)=>Object.assign(l,f.lines[String(l.id||i)]||{}));return x}
function fingerprint(d){const x={};Object.keys(MAP).forEach(k=>x[k]=(d[k]||[]).map(safe).sort((a,b)=>String(a.id||'').localeCompare(String(b.id||''))));return JSON.stringify(x)}
function inject(){if($('#v8Auth'))return;const s=document.createElement('style');s.textContent=`#v8Auth{position:fixed;inset:0;z-index:99999;background:#0d1015;display:grid;place-items:center;padding:20px;color:#fff;font-family:Inter,Arial}#v8Auth.hide{display:none}.v8card{width:min(430px,100%);background:#181b21;border:1px solid #30353e;border-radius:20px;padding:28px}.v8mark{width:56px;height:56px;border-radius:15px;background:#ed1c24;display:grid;place-items:center;font-weight:900;font-size:21px;margin-bottom:16px}.v8card h1{margin:0 0 5px}.v8card p{color:#9da6b3;font-size:12px;margin:0 0 18px}.v8card label{display:block;font-size:11px;margin:12px 0}.v8card input{width:100%;box-sizing:border-box;padding:12px;border-radius:10px;border:1px solid #333943;background:#0f1217;color:#fff;margin-top:6px}.v8card button{width:100%;padding:12px;border:0;border-radius:10px;background:#ed1c24;color:#fff;font-weight:800}.v8err{min-height:18px;color:#ff6b72;font-size:11px;margin-top:9px}.v8user{margin:8px 0;padding:9px;border:1px solid var(--line);border-radius:9px;font-size:10px}.v8user b{display:block;font-size:11px}.v8hidden{display:none!important}.v8users{overflow:auto}.v8users table{min-width:760px}.v8perms{grid-column:1/-1;display:flex;gap:18px;flex-wrap:wrap}.v8perms label{display:flex;gap:7px;align-items:center}`;document.head.appendChild(s);const a=document.createElement('div');a.id='v8Auth';a.innerHTML=`<div class="v8card"><div class="v8mark">DL</div><h1>Design Line ERP</h1><p>Version 8 • Secure Boss / Staff Login</p><form id="v8Form"><label>Email<input id="v8Email" type="email" required autocomplete="username"></label><label>Password<input id="v8Pass" type="password" required autocomplete="current-password"></label><button id="v8Btn">Login</button><div id="v8Err" class="v8err"></div></form></div>`;document.body.prepend(a);$('.app-shell').style.visibility='hidden';$('#v8Form').onsubmit=login}
async function login(e){e.preventDefault();const b=$('#v8Btn'),er=$('#v8Err');er.textContent='';b.disabled=true;try{await auth.signInWithEmailAndPassword($('#v8Email').value.trim(),$('#v8Pass').value)}catch(x){er.textContent=(x.message||'Login failed').replace('Firebase: ','')}finally{b.disabled=false}}
function showApp(on){$('.app-shell').style.visibility=on?'visible':'hidden';$('#v8Auth').classList.toggle('hide',on)}
function resetRoleUI(){$('#v8User')?.remove();$('#v8Logout')?.remove();$('#v8UsersNav')?.remove();const r=$('#roleSelect');if(r){r.disabled=false;delete r.dataset.v8lock}$$('.v8hidden').forEach(x=>x.classList.remove('v8hidden'))}
function roleUI(){if(!prof)return;const r=$('#roleSelect'),target=boss()?'admin':'staff';if(r&&r.dataset.v8lock!=='1'){r.value=target;r.dispatchEvent(new Event('change',{bubbles:true}));r.disabled=true;r.dataset.v8lock='1';r.closest('.field')?.classList.add('v8hidden')}const sb=$('.sidebar-bottom');if(sb){let box=$('#v8User');if(!box){box=document.createElement('div');box.id='v8User';box.className='v8user';sb.prepend(box)}box.innerHTML=`<b>${E(prof.name||user.email)}</b>${E(boss()?'Boss / Admin':'Staff')} • ${E(user.email||'')}`;if(!$('#v8Logout')){const b=document.createElement('button');b.id='v8Logout';b.className='ghost full';b.textContent='Logout';b.onclick=()=>auth.signOut();sb.appendChild(b)}}$('[data-view="settings"]')?.classList.toggle('v8hidden',!boss());$('[data-view="reports"]')?.classList.toggle('v8hidden',!can('canViewReports'));$('[data-view="expenses"]')?.classList.toggle('v8hidden',!can('canViewReports'));if(boss())usersNav();sensitive()}
function sensitive(){if(!prof)return;if(!boss()){$$('.admin-only').forEach(x=>x.classList.add('v8hidden'));$$('#dynamicForm .v7-section').forEach(s=>{const t=s.textContent.toLowerCase();if(t.includes('vendor / purchase')||t.includes('production cost')){s.classList.add('v8hidden');let n=s.nextElementSibling;while(n&&!n.classList.contains('v7-section')&&!n.classList.contains('v7-item-total')){n.classList.add('v8hidden');n=n.nextElementSibling}}});$$('#dynamicForm .field').forEach(f=>{const t=(f.querySelector('span')?.textContent||'').toLowerCase();if(/vendor|purchase cost|printing cost|plate rate|die cost|desired profit/.test(t))f.classList.add('v8hidden')})}if(!can('canDelete'))$$('button').filter(b=>b.textContent.trim().toLowerCase()==='delete').forEach(b=>b.classList.add('v8hidden'));if(!can('canPayVendors'))$$('button').filter(b=>/pay vendor/i.test(b.textContent)).forEach(b=>b.classList.add('v8hidden'))}
function usersNav(){if($('#v8UsersNav'))return;const n=$('.sidebar nav'),b=document.createElement('button');b.id='v8UsersNav';b.className='nav-btn';b.innerHTML='<span>♟</span> Users';b.onclick=openUsers;n.appendChild(b)}
async function openUsers(){try{const s=await fs.collection('users').get(),rows=s.docs.map(d=>({uid:d.id,...d.data()})).filter(x=>x.role);const f=$('#dynamicForm');$('#modalTitle').textContent='Users & Permissions — Version 8';f.innerHTML=`<div class="v7-doc"><div class="v7-addbar"><b>Boss / Staff Accounts</b><button type="button" class="primary" id="v8Add">+ Add Staff</button></div><div class="v8users"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Reports</th><th>Vendor Pay</th><th>Delete</th><th>Action</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${E(x.name||'')}</td><td>${E(x.email||'')}</td><td>${E(x.role)}</td><td>${x.active?'Active':'Inactive'}</td><td>${x.canViewReports?'Yes':'No'}</td><td>${x.canPayVendors?'Yes':'No'}</td><td>${x.canDelete?'Yes':'No'}</td><td>${x.uid===user.uid?'Current user':`<button type="button" class="icon-btn" data-v8toggle="${E(x.uid)}" data-on="${x.active?'1':'0'}">${x.active?'Deactivate':'Activate'}</button> <button type="button" class="icon-btn" data-v8reset="${E(x.email||'')}">Reset Password</button>`}</td></tr>`).join('')}</tbody></table></div></div>`;f.onsubmit=e=>e.preventDefault();$('#modal').classList.add('open');$('#v8Add').onclick=staffForm;f.querySelectorAll('[data-v8toggle]').forEach(b=>b.onclick=async()=>{await fs.collection('users').doc(b.dataset.v8toggle).update({active:b.dataset.on!=='1'});openUsers()});f.querySelectorAll('[data-v8reset]').forEach(b=>b.onclick=async()=>{try{await auth.sendPasswordResetEmail(b.dataset.v8reset);toast('Password reset email sent')}catch(e){toast(e.message,true)}})}catch(e){toast(e.message,true)}}
function staffForm(){const f=$('#dynamicForm');$('#modalTitle').textContent='Add Staff User';f.innerHTML=`<div class="form-grid"><label class="field"><span>Name</span><input name="name" required></label><label class="field"><span>Email</span><input name="email" type="email" required></label><label class="field"><span>Temporary Password</span><input name="password" type="password" minlength="6" required></label><div class="v8perms"><label><input type="checkbox" name="canViewReports"> Reports / Expenses</label><label><input type="checkbox" name="canPayVendors"> Vendor Payment</label><label><input type="checkbox" name="canDelete"> Delete Records</label></div><div class="form-actions full-span"><button class="primary">Create Staff</button></div></div>`;f.onsubmit=createStaff}
async function createStaff(e){e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries());try{let a=firebase.apps.find(x=>x.name==='DLStaff');if(!a)a=firebase.initializeApp(CFG,'DLStaff');const sa=a.auth();await sa.setPersistence(firebase.auth.Auth.Persistence.NONE);const c=await sa.createUserWithEmailAndPassword(d.email.trim(),d.password);await sa.signOut();await fs.collection('users').doc(c.user.uid).set({name:d.name.trim(),email:d.email.trim(),role:'staff',active:true,canManageUsers:false,canViewReports:!!d.canViewReports,canPayVendors:!!d.canPayVendors,canDelete:!!d.canDelete});toast('Staff account created');openUsers()}catch(x){toast(x.message,true)}}
async function audit(action){try{await fs.collection('auditLogs').add({action,uid:user.uid,email:user.email||'',role:prof.role,at:new Date().toISOString()})}catch{}}
async function cloud(){const out={};let any=false;for(const[k,c]of Object.entries(MAP)){if(!readKey(k))continue;try{const s=await fs.collection(c).get();out[k]=s.docs.map(d=>({id:d.id,...d.data()}));if(out[k].length)any=true}catch(e){console.warn(c,e.message)}}if(boss()){try{const s=await fs.collection('users').where('type','==','finance').get(),m={};s.docs.forEach(d=>{const x=d.data();m[x.kind+':'+x.recordId]=x});if(out.orders)out.orders=out.orders.map(o=>merge(o,m['order:'+o.id]));if(out.quotes)out.quotes=out.quotes.map(q=>merge(q,m['quote:'+q.id]))}catch(e){console.warn(e.message)}}return{out,any}}
async function hydrate(reload=true){const l=read(),c=await cloud();if(c.any){const m={...l,...c.out},a=fingerprint(l),b=fingerprint(m);if(a!==b){write(m);last=b;if(reload){sessionStorage.setItem('v8r','1');location.reload()}return true}}else if(boss()&&Object.keys(MAP).some(k=>(l[k]||[]).length))await sync(l,true);status('● Firebase Connected');return false}
function queueSync(){clearTimeout(timer);timer=setTimeout(()=>sync(read()),1200)}
async function batch(ops){for(let i=0;i<ops.length;i+=400){const b=fs.batch();ops.slice(i,i+400).forEach(o=>{const r=fs.collection(o.c).doc(o.id);o.del?b.delete(r):b.set(r,o.d)});await b.commit()}}
async function sync(d,force=false){if(busy||!ready)return;const fp=fingerprint(d);if(!force&&fp===last)return;busy=true;status('● Firebase Syncing');try{const ops=[];for(const[k,c]of Object.entries(MAP)){if(!writeKey(k))continue;const arr=(d[k]||[]).filter(x=>x?.id);let remote=[];if(readKey(k)){try{remote=(await fs.collection(c).get()).docs.map(x=>x.id)}catch{}}const ids=new Set(arr.map(x=>String(x.id)));arr.forEach(x=>{let z={pub:safe(x)};if(k==='orders')z=split(x,'order');if(k==='quotes')z=split(x,'quote');ops.push({c,id:String(x.id),d:z.pub});if(boss()&&(k==='orders'||k==='quotes'))ops.push({c:'users',id:`finance_${k==='orders'?'order':'quote'}__${x.id}`,d:z.fin})});if(delKey(k))remote.filter(id=>!ids.has(id)).forEach(id=>ops.push({c,id,del:true}))}if(boss()){try{const q=await fs.collection('users').where('type','==','finance').get(),valid=new Set([...(d.orders||[]).map(x=>'finance_order__'+x.id),...(d.quotes||[]).map(x=>'finance_quote__'+x.id)]);q.docs.forEach(x=>{if(!valid.has(x.id))ops.push({c:'users',id:x.id,del:true})})}catch{}}await batch(ops);last=fp;status('● Firebase Synced')}catch(e){status('● Firebase Sync Error',true);toast(e.message,true)}finally{busy=false}}
function realtime(){unsubs.forEach(x=>x());unsubs=[];for(const[k,c]of Object.entries(MAP)){if(!readKey(k))continue;let first=true;unsubs.push(fs.collection(c).onSnapshot(()=>{if(first){first=false;return}clearTimeout(remoteTimer);remoteTimer=setTimeout(()=>hydrate(true),800)}))}unsubs.push(fs.collection('users').doc(user.uid).onSnapshot(d=>{if(!d.exists||d.data().active!==true)return auth.signOut();prof={uid:user.uid,email:user.email,...d.data()};roleUI()}))}
function guard(e){if(!prof)return;const b=e.target.closest?.('button');if(!b)return;const t=b.textContent.trim().toLowerCase();if(!can('canDelete')&&t==='delete'){e.preventDefault();e.stopImmediatePropagation();toast('Delete permission disabled',true)}if(!can('canPayVendors')&&t.includes('pay vendor')){e.preventDefault();e.stopImmediatePropagation();toast('Vendor payment permission disabled',true)}}
async function authState(u){ready=false;prof=null;user=u;unsubs.forEach(x=>{try{x()}catch{}});unsubs=[];if(!u){resetRoleUI();showApp(false);status('● Login Required',true);return}try{const d=await fs.collection('users').doc(u.uid).get();if(!d.exists)throw Error('User profile not configured in Firestore');prof={uid:u.uid,email:u.email,...d.data()};if(prof.active!==true)throw Error('This account is inactive');ready=true;roleUI();const skip=sessionStorage.getItem('v8r');if(skip)sessionStorage.removeItem('v8r');const changed=await hydrate(!skip);if(changed&&!skip)return;showApp(true);realtime();audit('login');status('● Firebase Connected')}catch(e){toast(e.message,true);await auth.signOut()}}
function init(){inject();if(typeof firebase==='undefined'){toast('Firebase SDK failed to load',true);return}const app=firebase.apps[0]||firebase.initializeApp(CFG);auth=app.auth();fs=app.firestore();auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL).catch(()=>{});document.addEventListener('click',guard,true);new MutationObserver(()=>{if(prof)sensitive()}).observe(document.body,{childList:true,subtree:true});auth.onAuthStateChanged(authState)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();