(()=>{'use strict';
const KEY='designlineERP_v2';
const CFG={
  apiKey:'AIzaSyC8Hx-5PQHT3lNeRvMfSOIZnvm2IkEOBk8',
  authDomain:'designline-erp.firebaseapp.com',
  projectId:'designline-erp',
  storageBucket:'designline-erp.firebasestorage.app',
  messagingSenderId:'605680724271',
  appId:'1:605680724271:web:cb3184217ea69e1d8619da'
};
const MAP={customers:'customers',vendors:'vendors',orders:'orders',quotes:'quotations',payments:'payments',expenses:'expenses',vendorPayments:'vendorPayments'};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let app,auth,store,currentUser=null,profile=null,ready=false,suspendLocal=false,syncTimer=null,syncBusy=false,remoteTimer=null,unsubs=[];
let lastSynced='';
const originalSet=Storage.prototype.setItem;
Storage.prototype.setItem=function(k,v){originalSet.call(this,k,v);if(k===KEY&&!suspendLocal&&ready)queueSync();};
function localDB(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return{}}}
function writeLocal(db){suspendLocal=true;try{originalSet.call(localStorage,KEY,JSON.stringify(db))}finally{suspendLocal=false}}
function toast(msg,bad=false){const t=$('#toast');if(t){t.textContent=msg;t.classList.add('show');if(bad)t.style.background='#8b1b1f';setTimeout(()=>{t.classList.remove('show');t.style.background=''},2200)}}
function safe(o){return JSON.parse(JSON.stringify(o??{}))}
function roleBoss(){return profile?.role==='boss'}
function can(name){return roleBoss()||profile?.[name]===true}
function canReadKey(k){if(k==='vendorPayments')return can('canPayVendors')||can('canViewReports');if(k==='expenses')return can('canViewReports');return true}
function canWriteKey(k){if(k==='vendorPayments')return can('canPayVendors');return true}
function canDeleteKey(k){if(k==='vendorPayments')return roleBoss();return can('canDelete')}
function meaningful(db){return Object.keys(MAP).some(k=>Array.isArray(db[k])&&db[k].length>0)}
const FIN=['vendorCost','vendorBillRef','printingCost','plateQty','plateRate','dieCost','laminationCost','uvFoilCost','cuttingCost','bindingCost','packingCost','transportCost','desiredProfit'];
const N=x=>Number(x)||0;
function calcQuoteLine(x){const flex=['Flex Printing','Wallpaper + Fitting'].includes(x?.service),a=N(x.widthFt)&&N(x.heightFt)?N(x.widthFt)*N(x.heightFt)*Math.max(1,N(x.panels)||1):N(x.qty);if(flex)return a*N(x.rate)+N(x.designCharges)+N(x.fittingCharges)+N(x.otherCharges);if(x.service==='Passport Photos')return N(x.qty)*N(x.rate)+N(x.retouchCharges)+N(x.otherCharges);if(x.service==='ID / Document Print')return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.laminationCharges)+N(x.otherCharges);if(x.service==='Offset / Packaging'&&x.pricingMethod==='cost'){const c=N(x.printingCost)+N(x.plateQty)*N(x.plateRate)+N(x.dieCost)+N(x.laminationCost)+N(x.uvFoilCost)+N(x.cuttingCost)+N(x.bindingCost)+N(x.packingCost)+N(x.transportCost)+N(x.vendorCost);return c+N(x.designCharges)+N(x.otherCharges)+N(x.desiredProfit)}return N(x.qty)*N(x.rate)+N(x.designCharges)+N(x.finishingCharges)+N(x.fittingCharges)+N(x.otherCharges)}
function splitFinance(record,kind){const pub=safe(record),fin={type:'finance',kind,recordId:String(record.id),lines:{},updatedAt:new Date().toISOString()};const ls=(pub.lineItems||[]).length?pub.lineItems:[pub];ls.forEach((line,i)=>{const id=String(line.id||i),f={};FIN.forEach(k=>{if(line[k]!==undefined)f[k]=line[k]});if(kind==='quote'&&line.pricingMethod!==undefined)f.pricingMethod=line.pricingMethod;if(Object.keys(f).length)fin.lines[id]=f;if(kind==='quote'&&line.service==='Offset / Packaging'&&line.pricingMethod==='cost'){const total=calcQuoteLine(line),extras=N(line.designCharges)+N(line.otherCharges),qty=Math.max(1,N(line.qty));line.pricingMethod='rate';line.rate=Math.max(0,total-extras)/qty}FIN.forEach(k=>delete line[k])});if(!(pub.lineItems||[]).length){FIN.forEach(k=>delete pub[k]);if(kind==='quote'&&pub.service==='Offset / Packaging'&&record.pricingMethod==='cost'){pub.pricingMethod='rate'}}return{pub,fin}}
function mergeFinance(record,fin){if(!fin?.lines)return record;const r=safe(record),ls=(r.lineItems||[]).length?r.lineItems:[r];ls.forEach((line,i)=>{const id=String(line.id||i),f=fin.lines[id];if(f)Object.assign(line,f)});return r}
function normalize(db){const x={};for(const k of Object.keys(MAP)){x[k]=(db[k]||[]).map(safe).sort((a,b)=>String(a.id||'').localeCompare(String(b.id||'')))}return JSON.stringify(x)}
function setStatus(text,kind='ok'){const p=$('#storagePill');if(!p)return;p.textContent=text;p.style.color=kind==='bad'?'#ff6268':kind==='wait'?'#f5bd4f':'#39d98a'}
function injectShell(){
  const style=document.createElement('style');style.id='v8AuthStyle';style.textContent=`
  #v8Auth{position:fixed;inset:0;z-index:99999;background:radial-gradient(circle at 20% 10%,#301217 0,#111318 37%,#090b0f 100%);display:flex;align-items:center;justify-content:center;padding:22px;font-family:Inter,Arial,sans-serif;color:#fff}
  #v8Auth.hidden{display:none}.v8-login{width:min(440px,100%);background:#171a20;border:1px solid #2b3038;border-radius:22px;padding:30px;box-shadow:0 30px 80px #0009}.v8-logo{width:58px;height:58px;border-radius:16px;background:#ed1c24;display:grid;place-items:center;font-weight:900;font-size:22px;margin-bottom:18px}.v8-login h1{margin:0 0 6px;font-size:27px}.v8-login p{margin:0 0 22px;color:#9fa8b7;font-size:13px;line-height:1.5}.v8-field{display:block;margin:13px 0}.v8-field span{display:block;font-size:11px;color:#b5bdc9;font-weight:700;margin:0 0 7px}.v8-field input{width:100%;box-sizing:border-box;background:#0f1217;color:#fff;border:1px solid #323844;border-radius:11px;padding:13px 14px;outline:none}.v8-field input:focus{border-color:#ed1c24}.v8-login button{width:100%;border:0;border-radius:11px;padding:13px 16px;background:#ed1c24;color:#fff;font-weight:800;cursor:pointer;margin-top:7px}.v8-login button:disabled{opacity:.6}.v8-err{min-height:18px;color:#ff6b71;font-size:11px;margin-top:10px}.v8-foot{margin-top:18px!important;font-size:10px!important;text-align:center}.v8-userbox{margin-top:10px;padding:10px 11px;border:1px solid var(--line,#30343c);border-radius:10px;font-size:11px}.v8-userbox b{display:block;color:#fff}.v8-userbox span{color:var(--muted,#949daa)}#v8Logout{margin-top:8px;width:100%}.v8-users-table{overflow:auto;border:1px solid var(--line);border-radius:12px;margin-top:12px}.v8-users-table table{min-width:760px}.v8-perms{display:grid;grid-template-columns:repeat(2,1fr);gap:8px 14px;grid-column:1/-1}.v8-check{display:flex;gap:8px;align-items:center;font-size:12px}.v8-check input{width:auto!important}.v8-staff-hidden{display:none!important}`;
  document.head.appendChild(style);
  const box=document.createElement('div');box.id='v8Auth';box.innerHTML=`<div class="v8-login"><div class="v8-logo">DL</div><h1>Design Line ERP</h1><p>Version 8 • Secure Boss / Staff Login</p><form id="v8LoginForm"><label class="v8-field"><span>Email</span><input id="v8Email" type="email" autocomplete="username" required></label><label class="v8-field"><span>Password</span><input id="v8Password" type="password" autocomplete="current-password" required></label><button id="v8LoginBtn">Login</button><div class="v8-err" id="v8LoginErr"></div></form><p class="v8-foot">Authorized users only • Firebase Authentication</p></div>`;document.body.prepend(box);
  const shell=$('.app-shell');if(shell)shell.style.visibility='hidden';
  $('#v8LoginForm').addEventListener('submit',login);
}
async function login(e){e.preventDefault();const btn=$('#v8LoginBtn'),err=$('#v8LoginErr');err.textContent='';btn.disabled=true;btn.textContent='Signing in...';try{await auth.signInWithEmailAndPassword($('#v8Email').value.trim(),$('#v8Password').value)}catch(ex){err.textContent=ex?.message?.replace('Firebase: ','')||'Login failed'}finally{btn.disabled=false;btn.textContent='Login'}}
function showLogin(msg=''){const shell=$('.app-shell');if(shell)shell.style.visibility='hidden';$('#v8Auth')?.classList.remove('hidden');if(msg&&$('#v8LoginErr'))$('#v8LoginErr').textContent=msg}
function showApp(){const shell=$('.app-shell');if(shell)shell.style.visibility='visible';$('#v8Auth')?.classList.add('hidden')}
async function getProfile(u){const d=await store.collection('users').doc(u.uid).get();if(!d.exists)throw new Error('Your ERP user profile is not configured in Firestore.');const p={uid:u.uid,email:u.email,...d.data()};if(p.active!==true)throw new Error('This ERP account is inactive.');return p}
function applyRole(){
  if(!profile)return;const rs=$('#roleSelect');if(rs){const target=roleBoss()?'admin':'staff';if(rs.dataset.v8Locked!=='1'){rs.value=target;rs.dispatchEvent(new Event('change',{bubbles:true}));rs.disabled=true;rs.dataset.v8Locked='1'}const f=rs.closest('.field');if(f)f.classList.add('v8-staff-hidden')}
  const sb=$('.sidebar-bottom');if(sb&&!$('#v8UserBox')){const b=document.createElement('div');b.id='v8UserBox';b.className='v8-userbox';b.innerHTML=`<b>${E(profile.name||currentUser.email)}</b><span>${E(roleBoss()?'Boss / Admin':'Staff')} • ${E(currentUser.email||'')}</span>`;sb.prepend(b);const out=document.createElement('button');out.id='v8Logout';out.className='ghost';out.textContent='Logout';out.onclick=()=>auth.signOut();sb.appendChild(out)}
  const settings=$('[data-view="settings"]');if(settings)settings.classList.toggle('v8-staff-hidden',!roleBoss());
  const reports=$('[data-view="reports"]');if(reports)reports.classList.toggle('v8-staff-hidden',!can('canViewReports'));
  const expenses=$('[data-view="expenses"]');if(expenses)expenses.classList.toggle('v8-staff-hidden',!can('canViewReports'));
  injectUsersNav();enforceSensitiveUI();
}
function enforceSensitiveUI(){if(!profile)return;const staff=!roleBoss();if(staff){
  $$('.admin-only').forEach(x=>x.classList.add('v8-staff-hidden'));
  $$('#dynamicForm .v7-section').forEach(sec=>{const t=sec.textContent.toLowerCase();if(t.includes('vendor / purchase')||t.includes('production cost')||t.includes('offset production cost')){sec.classList.add('v8-staff-hidden');let n=sec.nextElementSibling;while(n&&!n.classList.contains('v7-section')&&!n.classList.contains('v7-item-total')){n.classList.add('v8-staff-hidden');n=n.nextElementSibling}}});
  $$('#dynamicForm .field').forEach(f=>{const t=(f.querySelector('span')?.textContent||'').toLowerCase();if(t.includes('vendor')||t.includes('purchase cost')||t.includes('plate rate')||t.includes('die cost')||t.includes('printing cost')||t.includes('desired profit'))f.classList.add('v8-staff-hidden')});
 }
 if(!can('canDelete'))$$('button').filter(b=>/^delete$/i.test(b.textContent.trim())).forEach(b=>b.classList.add('v8-staff-hidden'));
 if(!can('canPayVendors'))$$('button').filter(b=>/pay vendor/i.test(b.textContent)).forEach(b=>b.classList.add('v8-staff-hidden'));
}
function injectUsersNav(){if(!roleBoss()||$('#v8UsersNav'))return;const nav=$('.sidebar nav');if(!nav)return;const b=document.createElement('button');b.id='v8UsersNav';b.className='nav-btn';b.innerHTML='<span>♟</span> Users';b.addEventListener('click',openUsers);nav.appendChild(b)}
async function openUsers(){try{const snap=await store.collection('users').get(),rows=snap.docs.map(d=>({uid:d.id,...d.data()})).filter(u=>u.type!=='finance'&&u.role);const f=$('#dynamicForm');$('#modalTitle').textContent='Users & Permissions — Version 8';f.innerHTML=`<div class="v7-doc"><div class="v7-addbar"><div><b>Boss / Staff Accounts</b><div class="v7-summary">Firebase Authentication + Firestore roles</div></div><button type="button" class="primary" id="v8AddStaff">+ Add Staff</button></div><div class="v8-users-table"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Reports</th><th>Vendor Pay</th><th>Delete</th><th>Action</th></tr></thead><tbody>${rows.map(u=>`<tr><td>${E(u.name||'')}</td><td>${E(u.email||'')}</td><td>${E(u.role||'staff')}</td><td>${u.active===true?'Active':'Inactive'}</td><td>${u.canViewReports?'Yes':'No'}</td><td>${u.canPayVendors?'Yes':'No'}</td><td>${u.canDelete?'Yes':'No'}</td><td>${u.uid===currentUser.uid?'<span class="v7-badge">Current user</span>':`<button type="button" class="icon-btn" data-v8-toggle="${E(u.uid)}" data-active="${u.active===true?'1':'0'}">${u.active===true?'Deactivate':'Activate'}</button><button type="button" class="icon-btn" data-v8-reset="${E(u.email||'')}">Reset Password</button>`}</td></tr>`).join('')}</tbody></table></div><div class="v7-actions"><button type="button" class="ghost" id="v8CloseUsers">Close</button></div></div>`;f.onsubmit=e=>e.preventDefault();$('#modal').classList.add('open');$('#v8CloseUsers').onclick=()=>$('#modal').classList.remove('open');$('#v8AddStaff').onclick=staffForm;f.querySelectorAll('[data-v8-toggle]').forEach(b=>b.onclick=()=>toggleUser(b.dataset.v8Toggle,b.dataset.active!=='1'));f.querySelectorAll('[data-v8-reset]').forEach(b=>b.onclick=()=>sendReset(b.dataset.v8Reset))}catch(e){toast(e.message,true)}}
function staffForm(){const f=$('#dynamicForm');$('#modalTitle').textContent='Add Staff User';f.innerHTML=`<div class="form-grid"><label class="field"><span>Name</span><input name="name" required></label><label class="field"><span>Email</span><input name="email" type="email" required></label><label class="field"><span>Temporary Password</span><input name="password" type="password" minlength="6" required></label><label class="field"><span>Role</span><input value="staff" disabled></label><div class="v8-perms"><label class="v8-check"><input name="canViewReports" type="checkbox"> View Reports / Expenses</label><label class="v8-check"><input name="canPayVendors" type="checkbox"> Pay Vendors</label><label class="v8-check"><input name="canDelete" type="checkbox"> Delete Records</label></div><div class="form-actions full-span"><button type="button" class="ghost" id="v8BackUsers">Back</button><button class="primary">Create Staff Account</button></div></div>`;$('#v8BackUsers').onclick=openUsers;f.onsubmit=createStaff}
async function createStaff(e){e.preventDefault();if(!roleBoss())return;const f=e.currentTarget,d=Object.fromEntries(new FormData(f).entries()),btn=f.querySelector('button.primary');btn.disabled=true;try{let sec=firebase.apps.find(a=>a.name==='DLUserCreator');if(!sec)sec=firebase.initializeApp(CFG,'DLUserCreator');const a=sec.auth();await a.setPersistence(firebase.auth.Auth.Persistence.NONE);const cred=await a.createUserWithEmailAndPassword(d.email.trim(),d.password);await a.signOut();await store.collection('users').doc(cred.user.uid).set({name:d.name.trim(),email:d.email.trim(),role:'staff',active:true,canManageUsers:false,canViewReports:!!d.canViewReports,canPayVendors:!!d.canPayVendors,canDelete:!!d.canDelete,createdAt:new Date().toISOString(),createdBy:currentUser.uid});await audit('user_created',{targetUid:cred.user.uid,targetEmail:d.email.trim()});toast('Staff account created');openUsers()}catch(ex){toast(ex.message,true)}finally{btn.disabled=false}}
async function toggleUser(uid,active){if(!roleBoss())return;await store.collection('users').doc(uid).update({active});await audit(active?'user_activated':'user_deactivated',{targetUid:uid});openUsers()}
async function sendReset(email){if(!email)return toast('User email missing',true);try{await auth.sendPasswordResetEmail(email);toast('Password reset email sent')}catch(e){toast(e.message,true)}}
async function audit(action,details={}){try{if(!currentUser||!profile)return;await store.collection('auditLogs').add({action,uid:currentUser.uid,email:currentUser.email||'',name:profile.name||'',role:profile.role||'',details:safe(details),at:new Date().toISOString()})}catch(e){console.warn('Audit:',e.message)}}
async function fetchCloud(){const out={};let any=false;for(const [k,col] of Object.entries(MAP)){if(!canReadKey(k))continue;try{const s=await store.collection(col).get();out[k]=s.docs.filter(d=>!d.id.startsWith('_')).map(d=>({id:d.id,...d.data()}));if(out[k].length)any=true}catch(e){console.warn('Firestore read',col,e.message)}}if(roleBoss()){try{const fs=await store.collection('users').where('type','==','finance').get(),fm={};fs.docs.forEach(d=>{const x=d.data();fm[`${x.kind}:${x.recordId}`]=x});if(out.orders)out.orders=out.orders.map(o=>mergeFinance(o,fm[`order:${o.id}`]));if(out.quotes)out.quotes=out.quotes.map(q=>mergeFinance(q,fm[`quote:${q.id}`]))}catch(e){console.warn('Finance read',e.message)}}return{out,any}}
async function hydrate(reason='initial'){if(!ready||!currentUser||!profile)return false;setStatus('● Firebase Loading','wait');const local=localDB(),{out,any}=await fetchCloud();if(any){const merged={...local};for(const k of Object.keys(out))merged[k]=out[k];const before=normalize(local),after=normalize(merged);if(before!==after){writeLocal(merged);lastSynced=after;setStatus('● Firebase Synced');if(reason!=='silent'){sessionStorage.setItem('dlv8-reload','1');location.reload()}return true}}else if(roleBoss()&&meaningful(local)){await syncAll(local,true)}setStatus('● Firebase Connected');return false}
function queueSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncAll(localDB(),false),1100)}
async function writeOps(ops){for(let i=0;i<ops.length;i+=400){const b=store.batch();for(const op of ops.slice(i,i+400)){const ref=store.collection(op.col).doc(op.id);op.type==='delete'?b.delete(ref):b.set(ref,op.data,false)}await b.commit()}}
async function syncAll(db,force=false){if(syncBusy||!ready||!currentUser||!profile)return;const fp=normalize(db);if(!force&&fp===lastSynced)return;syncBusy=true;setStatus('● Firebase Syncing','wait');try{const ops=[];for(const [k,col] of Object.entries(MAP)){if(!canWriteKey(k))continue;const arr=(db[k]||[]).filter(x=>x&&x.id);let remote=[];if(canReadKey(k)){try{const s=await store.collection(col).get();remote=s.docs.filter(d=>!d.id.startsWith('_')).map(d=>d.id)}catch{remote=[]}}const ids=new Set(arr.map(x=>String(x.id)));arr.forEach(x=>{let data=safe(x);if(k==='orders'){const z=splitFinance(x,'order');data=z.pub;if(roleBoss())ops.push({type:'set',col:'users',id:'finance_order__'+String(x.id),data:z.fin})}else if(k==='quotes'){const z=splitFinance(x,'quote');data=z.pub;if(roleBoss())ops.push({type:'set',col:'users',id:'finance_quote__'+String(x.id),data:z.fin})}ops.push({type:'set',col,id:String(x.id),data})});if(canDeleteKey(k))remote.filter(id=>!ids.has(id)).forEach(id=>ops.push({type:'delete',col,id}))}
if(roleBoss()){try{const fs=await store.collection('users').where('type','==','finance').get();const valid=new Set([...(db.orders||[]).map(o=>'finance_order__'+String(o.id)),...(db.quotes||[]).map(q=>'finance_quote__'+String(q.id))]);fs.docs.forEach(d=>{if(!valid.has(d.id))ops.push({type:'delete',col:'users',id:d.id})})}catch(e){console.warn('Finance cleanup',e.message)}}
await writeOps(ops);lastSynced=fp;setStatus('● Firebase Synced')}catch(e){console.error(e);setStatus('● Firebase Sync Error','bad');toast('Firebase sync: '+e.message,true)}finally{syncBusy=false}}
function startRealtime(){unsubs.forEach(f=>{try{f()}catch{}});unsubs=[];for(const [k,col] of Object.entries(MAP)){if(!canReadKey(k))continue;let first=true;const u=store.collection(col).onSnapshot(()=>{if(first){first=false;return}clearTimeout(remoteTimer);remoteTimer=setTimeout(()=>hydrate('remote'),700)},e=>console.warn('Realtime',col,e.message));unsubs.push(u)}const up=store.collection('users').doc(currentUser.uid).onSnapshot(d=>{if(!d.exists)return;const n={uid:currentUser.uid,email:currentUser.email,...d.data()};if(n.active!==true){auth.signOut();return}profile=n;applyRole()});unsubs.push(up)}
function blockUnauthorized(e){if(!profile)return;const b=e.target.closest?.('button');if(!b)return;const txt=b.textContent.trim().toLowerCase();if(!can('canDelete')&&txt==='delete'){e.preventDefault();e.stopImmediatePropagation();return toast('Delete permission is disabled for this user',true)}if(!can('canPayVendors')&&txt.includes('pay vendor')){e.preventDefault();e.stopImmediatePropagation();return toast('Vendor payment permission is disabled',true)}if(!roleBoss()&&(b.id==='resetDemoBtn'||b.id==='saveSettingsBtn'||b.id==='saveApiBtn')){e.preventDefault();e.stopImmediatePropagation();toast('Boss permission required',true)}}
async function authChanged(u){ready=false;profile=null;currentUser=u;unsubs.forEach(f=>{try{f()}catch{}});unsubs=[];if(!u){showLogin();setStatus('● Login Required','bad');return}try{profile=await getProfile(u);ready=true;applyRole();const reloaded=sessionStorage.getItem('dlv8-reload');if(reloaded)sessionStorage.removeItem('dlv8-reload');const changed=await hydrate(reloaded?'silent':'initial');if(changed&&!reloaded)return;showApp();startRealtime();await audit('login',{ua:navigator.userAgent.slice(0,120)});setStatus('● Firebase Connected')}catch(e){console.error(e);await auth.signOut();showLogin(e.message)}}
function init(){injectShell();if(typeof firebase==='undefined'){showLogin('Firebase SDK did not load. Refresh the page.');return}app=firebase.apps.length?firebase.app():firebase.initializeApp(CFG);auth=app.auth();store=app.firestore();auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL).catch(()=>{});document.addEventListener('click',blockUnauthorized,true);new MutationObserver(()=>{if(profile){applyRole();enforceSensitiveUI()}}).observe(document.body,{childList:true,subtree:true});auth.onAuthStateChanged(authChanged)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();