(()=>{'use strict';
const K='designlineERP_v2',$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],N=x=>Number(x)||0,R=x=>'Rs '+N(x).toLocaleString('en-PK'),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=()=>{try{return JSON.parse(localStorage.getItem(K))||{}}catch{return{}}};
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1900)}
function phonePK(p){return String(p||'').replace(/\D/g,'').replace(/^0/,'92')}
function lines(o){return Array.isArray(o?.lineItems)&&o.lineItems.length?o.lineItems:[o||{}]}
function vendorCost(l){if(l?.service==='Offset / Packaging')return N(l.printingCost)+N(l.plateQty)*N(l.plateRate)+N(l.dieCost)+N(l.laminationCost)+N(l.uvFoilCost)+N(l.cuttingCost)+N(l.bindingCost)+N(l.packingCost)+N(l.transportCost)+N(l.vendorCost);return N(l?.vendorCost)}
function orderCode(o){return o.orderNo?'ORD-'+String(N(o.orderNo)).padStart(4,'0'):(o.id||'—')}
function vendorStatement(id){const db=read(),v=(db.vendors||[]).find(x=>x.id===id);if(!v)return'';const customers=db.customers||[],jobs=[];(db.orders||[]).filter(o=>o.status!=='Cancelled').forEach(o=>lines(o).forEach(l=>{if(l.vendorId===id)jobs.push({date:o.date||'—',order:orderCode(o),customer:customers.find(c=>c.id===o.customerId)?.name||'Unknown',item:l.item||l.service||'Job',ref:l.vendorBillRef||l.purchaseBillRef||'',cost:vendorCost(l)})}));const pays=(db.vendorPayments||[]).filter(p=>p.vendorId===id).slice().sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))),totalBill=jobs.reduce((a,x)=>a+N(x.cost),0),totalPaid=pays.reduce((a,x)=>a+N(x.amount),0),balance=Math.max(0,totalBill-totalPaid);
const jobText=jobs.length?jobs.map((x,i)=>`${i+1}. ${x.date} | ${x.order}\n   ${x.customer} — ${x.item}${x.ref?' | Ref: '+x.ref:''}\n   Bill: ${R(x.cost)}`).join('\n'):'No jobs / bills recorded.';
const payText=pays.length?pays.map((x,i)=>`${i+1}. ${x.date||'—'} | ${R(x.amount)} | ${x.method||'Cash'}${x.reference?' | Ref: '+x.reference:''}${x.note?' | '+x.note:''}`).join('\n'):'No payments recorded.';
return `DESIGN LINE AGENCY\nVENDOR PAYMENT INVOICE / STATEMENT\n\nVendor: ${v.name||'Vendor'}\nPhone: ${v.phone||'—'}\n\nJOBS / BILLS\n${jobText}\n\nPAYMENT HISTORY\n${payText}\n\n------------------------------\nTotal Vendor Bills: ${R(totalBill)}\nTotal Paid: ${R(totalPaid)}\nBalance Payable: ${R(balance)}\nPayment Entries: ${pays.length}\n------------------------------\n\nPlease check and confirm.\nDesign Line Agency`;}
function sendVendor(id){const db=read(),v=(db.vendors||[]).find(x=>x.id===id);if(!v)return;if(!v.phone)return toast('Vendor phone number missing');window.open(`https://wa.me/${phonePK(v.phone)}?text=${encodeURIComponent(vendorStatement(id))}`,'_blank')}
function removeQuotationUI(){const qnav=$('.nav-btn[data-view="quotations"]');qnav?.remove();$$('[data-jump="quotations"]').forEach(x=>x.remove());const q=$('#quotationsView');if(q){q.classList.add('v20-quotation-compat');q.setAttribute('aria-hidden','true');q.style.display='none'};if(q?.classList.contains('active'))openView('dashboard');for(const k of ['designlineERP_active_view_v11','designlineERP_active_view_v17'])if(sessionStorage.getItem(k)==='quotations')sessionStorage.setItem(k,'dashboard')}
function openView(v){const nav=$(`.nav-btn[data-view="${v}"]`);if(nav){nav.click();return}const target=$('#'+v+'View');if(!target)return;$$('.view').forEach(x=>x.classList.remove('active'));target.classList.add('active');$$('.nav-btn[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));const t=$('#pageTitle');if(t)t.textContent=v.charAt(0).toUpperCase()+v.slice(1)}
const mobileItems=[['dashboard','⌂','Home'],['orders','▤','Orders'],['customers','◉','Customers'],['vendors','◇','Vendors'],['expenses','↘','Expenses'],['reports','⌁','Reports']];
function mountMobileNav(){if($('#v20MobileNav'))return;const nav=document.createElement('nav');nav.id='v20MobileNav';nav.setAttribute('aria-label','Mobile navigation');nav.innerHTML=mobileItems.map(([v,i,l])=>`<button type="button" data-v20-view="${v}"><span class="v20-icon">${i}</span><span>${l}</span></button>`).join('');document.body.appendChild(nav);nav.addEventListener('click',e=>{const b=e.target.closest('[data-v20-view]');if(!b)return;openView(b.dataset.v20View);syncMobileNav()});syncMobileNav()}
function syncMobileNav(){const active=String($('.view.active')?.id||'dashboardView').replace(/View$/,'');$$('#v20MobileNav [data-v20-view]').forEach(b=>b.classList.toggle('active',b.dataset.v20View===active))}
function labelTables(){$$('table').forEach(table=>{const hs=[...table.querySelectorAll('thead th')].map(x=>x.textContent.trim());table.querySelectorAll('tbody tr').forEach(tr=>[...tr.children].forEach((td,i)=>{if(td.tagName==='TD')td.dataset.v20Label=hs[i]||''}))})}
function patchVendorButtons(){$$('#vendorsBody tr').forEach(tr=>{const edit=tr.querySelector('[data-a="editVendor"]');if(!edit)return;const id=edit.dataset.id,box=edit.closest('.row-actions')||edit.parentElement;if(!box||box.querySelector('[data-v20="vendorWA"]'))return;const b=document.createElement('button');b.type='button';b.className='icon-btn';b.dataset.v20='vendorWA';b.dataset.id=id;b.textContent='WhatsApp';box.appendChild(b)});
const title=$('#modalTitle'),pay=$('#dynamicForm [data-v7="vendorPay"]');if(title?.textContent.startsWith('Vendor Ledger')&&pay){const bar=pay.parentElement;bar.querySelector('[data-v17="vendorWA"]')?.remove();if(!bar.querySelector('[data-v20="vendorWA"]')){const b=document.createElement('button');b.type='button';b.className='ghost';b.dataset.v20='vendorWA';b.dataset.id=pay.dataset.id;b.textContent='WhatsApp Invoice';bar.insertBefore(b,pay)}}}
function setBrand(){const b=$('.brand span');if(b)b.textContent='Agency ERP • Cloud • V20'}
function click(e){const wa=e.target.closest?.('[data-v20="vendorWA"]');if(wa){e.preventDefault();e.stopImmediatePropagation();return sendVendor(wa.dataset.id)}if(e.target.closest?.('.nav-btn[data-view],[data-jump]'))setTimeout(syncMobileNav,30)}
let timer;function patch(){clearTimeout(timer);timer=setTimeout(()=>{removeQuotationUI();mountMobileNav();patchVendorButtons();labelTables();syncMobileNav();setBrand()},50)}
function init(){document.body.classList.add('v20-app');removeQuotationUI();mountMobileNav();patchVendorButtons();labelTables();setBrand();document.addEventListener('click',click,true);new MutationObserver(patch).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});window.addEventListener('resize',patch);setTimeout(patch,250);setTimeout(patch,900)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();